// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.appTypes;

import java.util.logging.Logger;

public class AppTypesPanel extends AppTypesPanelBase {
    private static Logger LOG = Logger.getLogger(AppTypesPanel.class.getName());
}
