// Generated by OABuilder

package com.viaoa.appstore.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class AppRuntimeSearchModel {
    private static Logger LOG = Logger.getLogger(AppRuntimeSearchModel.class.getName());
    
    protected Hub<AppRuntime> hub;  // search results
    protected Hub<AppRuntime> hubMultiSelect;
    protected Hub<AppRuntime> hubSearchFrom;  // hub (optional) to search from
    protected Hub<AppRuntimeSearch> hubAppRuntimeSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, AppRuntime> finder;
    
    // object used for search data
    protected AppRuntimeSearch appRuntimeSearch;
    
    public AppRuntimeSearchModel() {
    }
    
    public AppRuntimeSearchModel(Hub<AppRuntime> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<AppRuntime> getHub() {
        if (hub == null) {
            hub = new Hub<AppRuntime>(AppRuntime.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<AppRuntime> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<AppRuntime> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    AppRuntimeSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<AppRuntime> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(AppRuntime.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, AppRuntime> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, AppRuntime> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public AppRuntimeSearch getAppRuntimeSearch() {
        if (appRuntimeSearch != null) return appRuntimeSearch;
        appRuntimeSearch = new AppRuntimeSearch();
        return appRuntimeSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<AppRuntimeSearch> getAppRuntimeSearchHub() {
        if (hubAppRuntimeSearch == null) {
            hubAppRuntimeSearch = new Hub<AppRuntimeSearch>(AppRuntimeSearch.class);
            hubAppRuntimeSearch.add(getAppRuntimeSearch());
            hubAppRuntimeSearch.setPos(0);
        }
        return hubAppRuntimeSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses AppRuntimeSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<AppRuntime> sel = getAppRuntimeSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(AppRuntime appRuntime, Hub<AppRuntime> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<AppRuntime> hub) {
    }
}

