// Generated by OABuilder

package com.viaoa.appstore.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class PropertyValueSearchModel {
    private static Logger LOG = Logger.getLogger(PropertyValueSearchModel.class.getName());
    
    protected Hub<PropertyValue> hub;  // search results
    protected Hub<PropertyValue> hubMultiSelect;
    protected Hub<PropertyValue> hubSearchFrom;  // hub (optional) to search from
    protected Hub<PropertyValueSearch> hubPropertyValueSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, PropertyValue> finder;
    
    // object used for search data
    protected PropertyValueSearch propertyValueSearch;
    
    public PropertyValueSearchModel() {
    }
    
    public PropertyValueSearchModel(Hub<PropertyValue> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<PropertyValue> getHub() {
        if (hub == null) {
            hub = new Hub<PropertyValue>(PropertyValue.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<PropertyValue> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<PropertyValue> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    PropertyValueSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<PropertyValue> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(PropertyValue.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, PropertyValue> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, PropertyValue> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public PropertyValueSearch getPropertyValueSearch() {
        if (propertyValueSearch != null) return propertyValueSearch;
        propertyValueSearch = new PropertyValueSearch();
        return propertyValueSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<PropertyValueSearch> getPropertyValueSearchHub() {
        if (hubPropertyValueSearch == null) {
            hubPropertyValueSearch = new Hub<PropertyValueSearch>(PropertyValueSearch.class);
            hubPropertyValueSearch.add(getPropertyValueSearch());
            hubPropertyValueSearch.setPos(0);
        }
        return hubPropertyValueSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses PropertyValueSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<PropertyValue> sel = getPropertyValueSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(PropertyValue propertyValue, Hub<PropertyValue> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<PropertyValue> hub) {
    }
}

