// Generated by OABuilder

package com.viaoa.appstore.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class ServerApplicationSearchModel {
    private static Logger LOG = Logger.getLogger(ServerApplicationSearchModel.class.getName());
    
    protected Hub<ServerApplication> hub;  // search results
    protected Hub<ServerApplication> hubMultiSelect;
    protected Hub<ServerApplication> hubSearchFrom;  // hub (optional) to search from
    protected Hub<ServerApplicationSearch> hubServerApplicationSearch;  // search data, size=1, AO
    // references used in search
    protected Hub<ApplicationType> hubApplicationType;
    
    // finder used to find objects in a path
    protected OAFinder<?, ServerApplication> finder;
    
    // ObjectModels
    protected ApplicationTypeModel modelApplicationType;
    
    // SearchModels
    protected ApplicationTypeSearchModel modelApplicationTypeSearch;
    
    // object used for search data
    protected ServerApplicationSearch serverApplicationSearch;
    
    public ServerApplicationSearchModel() {
    }
    
    public ServerApplicationSearchModel(Hub<ServerApplication> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<ServerApplication> getHub() {
        if (hub == null) {
            hub = new Hub<ServerApplication>(ServerApplication.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<ServerApplication> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<ServerApplication> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    ServerApplicationSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<ServerApplication> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(ServerApplication.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, ServerApplication> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, ServerApplication> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public ServerApplicationSearch getServerApplicationSearch() {
        if (serverApplicationSearch != null) return serverApplicationSearch;
        serverApplicationSearch = new ServerApplicationSearch();
        return serverApplicationSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<ServerApplicationSearch> getServerApplicationSearchHub() {
        if (hubServerApplicationSearch == null) {
            hubServerApplicationSearch = new Hub<ServerApplicationSearch>(ServerApplicationSearch.class);
            hubServerApplicationSearch.add(getServerApplicationSearch());
            hubServerApplicationSearch.setPos(0);
        }
        return hubServerApplicationSearch;
    }
    public Hub<ApplicationType> getApplicationTypeHub() {
        if (hubApplicationType != null) return hubApplicationType;
        hubApplicationType = new Hub<>(ApplicationType.class);
        Hub<ApplicationType> hub = ModelDelegate.getApplicationTypes();
        HubCopy<ApplicationType> hc = new HubCopy<>(hub, hubApplicationType, false);
        hubApplicationType.setLinkHub(getServerApplicationSearchHub(), ServerApplicationSearch.P_ApplicationType); 
        return hubApplicationType;
    }
    
    public ApplicationTypeModel getApplicationTypeModel() {
        if (modelApplicationType != null) return modelApplicationType;
        modelApplicationType = new ApplicationTypeModel(getApplicationTypeHub());
        modelApplicationType.setDisplayName("Application Type");
        modelApplicationType.setPluralDisplayName("Application Types");
        modelApplicationType.setAllowNew(false);
        modelApplicationType.setAllowSave(true);
        modelApplicationType.setAllowAdd(false);
        modelApplicationType.setAllowRemove(false);
        modelApplicationType.setAllowClear(true);
        modelApplicationType.setAllowDelete(false);
        modelApplicationType.setAllowSearch(true);
        modelApplicationType.setAllowHubSearch(false);
        modelApplicationType.setAllowGotoEdit(true);
        return modelApplicationType;
    }
    
    public ApplicationTypeSearchModel getApplicationTypeSearchModel() {
        if (modelApplicationTypeSearch == null) {
            modelApplicationTypeSearch = new ApplicationTypeSearchModel();
            getServerApplicationSearch().setApplicationTypeSearch(modelApplicationTypeSearch.getApplicationTypeSearch());
        }
        return modelApplicationTypeSearch;
    }
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses ServerApplicationSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<ServerApplication> sel = getServerApplicationSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(ServerApplication serverApplication, Hub<ServerApplication> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<ServerApplication> hub) {
    }
}

