// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.appStoreServers;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.Logger;
import javax.swing.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;
import com.viaoa.jfc.control.*;
import com.viaoa.jfc.border.ShadowBorder;

public class AppStoreServersPanelBase {
    private static Logger LOG = Logger.getLogger(AppStoreServersPanelBase.class.getName());
    
    private JRadioButtonMenuItem mi; 
    private JToggleButton toggleButton;
    
    private JSplitPane splitPane;
    private OAOutlookBar outlookBar;
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    
    public static final String CARD_MyAppStoreServersBar = "MyAppStoreServersBar";
    
    protected MyAppStoreServersBar barMyAppStoreServers;
    
    public AppStoreServersPanelBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        splitPane = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, getOutlookBar(), cardPanel);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        splitPane.setResizeWeight(.05d);
        
        ImageIcon icon;
        icon = Resource.getJarIcon("appStoreServersBar.png");
        outlookBar.addBar(CARD_MyAppStoreServersBar, "My AppStore Servers", icon, new JScrollPane(getMyAppStoreServersBar().getTree()));
        cardPanel.add(getMyAppStoreServersBar().getPanel(), CARD_MyAppStoreServersBar);
    }
    
    public MyAppStoreServersBar getMyAppStoreServersBar() {
        if (barMyAppStoreServers != null) return barMyAppStoreServers;
        barMyAppStoreServers = new MyAppStoreServersBar();
        return barMyAppStoreServers;
    }
    
    public OAOutlookBar getOutlookBar() {
        if (outlookBar != null) return outlookBar;
        outlookBar = new OAOutlookBar() {
            @Override
            protected void onBarSelected(String barName) {
                cardLayout.show(cardPanel, barName);
            }
        };
        int w = OAJfcUtil.getCharWidth(23);
        outlookBar.setPreferredSize(new Dimension(w, 50));
        outlookBar.setBorder(new ShadowBorder());
        Dimension d = outlookBar.getMinimumSize();
        w = OAJfcUtil.getCharWidth(1);
        d.width = w;
        outlookBar.setMinimumSize(d);
        outlookBar.setMinimumSize(new Dimension(10,10));
        return outlookBar;
    }
    
    public JToggleButton getToggleButton() {
        if (toggleButton != null) return toggleButton;
        toggleButton = new JToggleButton("AppStore Servers");
        ImageIcon ii = Resource.getJarIcon("appStoreServersButton.png");
        toggleButton.setIcon(ii);
        toggleButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toggleButton.setHorizontalTextPosition(SwingConstants.CENTER);
        toggleButton.setMnemonic('A');
        toggleButton.setToolTipText("show the AppStore Servers panel");
        new HubChangeListener(ModelDelegate.getLocalAppUserHub(), AppUserPP.showAppStoreServers(), true) {
            @Override
            protected void onChange() {
                toggleButton.setVisible(getValue());
            }
        };
        return toggleButton;
    }
    
    public JRadioButtonMenuItem getMenuItem() {
        if (mi != null) return mi;
        mi = new JRadioButtonMenuItem();
        mi.setMnemonic(KeyEvent.VK_A);
        mi.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, InputEvent.ALT_MASK, false));
        mi.setText("AppStore Servers panel");
        mi.setToolTipText("show the AppStoreServers panel");
        new HubChangeListener(ModelDelegate.getLocalAppUserHub(), AppUserPP.showAppStoreServers(), true) {
            @Override
            protected void onChange() {
                mi.setVisible(getValue());
            }
        };
        return mi;
    }
    
    public JSplitPane getSplitPane() {
        return splitPane;
    }
    public JComponent getMainComponent() {
        return splitPane;
    }
}

