// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.admin;

import java.util.logging.Logger;

public class AdminPanel extends AdminPanelBase {
    private static Logger LOG = Logger.getLogger(AdminPanel.class.getName());
}
