// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.admin;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.Logger;
import javax.swing.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;
import com.viaoa.jfc.control.*;
import com.viaoa.jfc.border.ShadowBorder;

public class AdminPanelBase {
    private static Logger LOG = Logger.getLogger(AdminPanelBase.class.getName());
    
    private JRadioButtonMenuItem mi; 
    private JToggleButton toggleButton;
    
    private JSplitPane splitPane;
    private OAOutlookBar outlookBar;
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    
    public static final String CARD_UsersBar = "UsersBar";
    public static final String CARD_RuntimeBar = "RuntimeBar";
    
    protected UsersBar barUsers;
    protected RuntimeBar barRuntime;
    
    public AdminPanelBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        splitPane = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, getOutlookBar(), cardPanel);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        splitPane.setResizeWeight(.05d);
        
        ImageIcon icon;
        icon = Resource.getJarIcon("adminBar.png");
        outlookBar.addBar(CARD_UsersBar, "Users", icon, new JScrollPane(getUsersBar().getTree()));
        cardPanel.add(getUsersBar().getPanel(), CARD_UsersBar);
        icon = Resource.getJarIcon("adminBar.png");
        outlookBar.addBar(CARD_RuntimeBar, "Runtime", icon, new JScrollPane(getRuntimeBar().getTree()));
        cardPanel.add(getRuntimeBar().getPanel(), CARD_RuntimeBar);
    }
    
    public UsersBar getUsersBar() {
        if (barUsers != null) return barUsers;
        barUsers = new UsersBar();
        return barUsers;
    }
    public RuntimeBar getRuntimeBar() {
        if (barRuntime != null) return barRuntime;
        barRuntime = new RuntimeBar();
        return barRuntime;
    }
    
    public OAOutlookBar getOutlookBar() {
        if (outlookBar != null) return outlookBar;
        outlookBar = new OAOutlookBar() {
            @Override
            protected void onBarSelected(String barName) {
                cardLayout.show(cardPanel, barName);
            }
        };
        int w = OAJfcUtil.getCharWidth(23);
        outlookBar.setPreferredSize(new Dimension(w, 50));
        outlookBar.setBorder(new ShadowBorder());
        Dimension d = outlookBar.getMinimumSize();
        w = OAJfcUtil.getCharWidth(1);
        d.width = w;
        outlookBar.setMinimumSize(d);
        outlookBar.setMinimumSize(new Dimension(10,10));
        return outlookBar;
    }
    
    public JToggleButton getToggleButton() {
        if (toggleButton != null) return toggleButton;
        toggleButton = new JToggleButton("Admin");
        ImageIcon ii = Resource.getJarIcon("adminButton.png");
        toggleButton.setIcon(ii);
        toggleButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toggleButton.setHorizontalTextPosition(SwingConstants.CENTER);
        toggleButton.setMnemonic('A');
        toggleButton.setToolTipText("show the Admin panel");
        new HubChangeListener(ModelDelegate.getLocalAppUserHub(), AppUserPP.admin(), true) {
            @Override
            protected void onChange() {
                toggleButton.setVisible(getValue());
            }
        };
        return toggleButton;
    }
    
    public JRadioButtonMenuItem getMenuItem() {
        if (mi != null) return mi;
        mi = new JRadioButtonMenuItem();
        mi.setMnemonic(KeyEvent.VK_A);
        mi.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, InputEvent.ALT_MASK, false));
        mi.setText("Admin panel");
        mi.setToolTipText("show the Admin panel");
        new HubChangeListener(ModelDelegate.getLocalAppUserHub(), AppUserPP.admin(), true) {
            @Override
            protected void onChange() {
                mi.setVisible(getValue());
            }
        };
        return mi;
    }
    
    public JSplitPane getSplitPane() {
        return splitPane;
    }
    public JComponent getMainComponent() {
        return splitPane;
    }
}

