// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.admin;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.*;
import javax.swing.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;

public class RuntimeBarBase {
    private static Logger LOG = Logger.getLogger(RuntimeBarBase.class.getName());
    
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    protected OATree tree;
    
    public static final String CARD_Splash = "splash";
    public static final String CARD_AppServers = "AppServers";
    public static final String CARD_AppRuntimes = "AppRuntimes";
    public static final String CARD_ConnectedAppUserLogins = "ConnectedAppUserLogins";
    public static final String CARD_LastDayAppUserLogins = "LastDayAppUserLogins";
    public static final String CARD_AppUserErrors = "AppUserErrors";
    
    public RuntimeBarBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        setup();
    }
    
    public JPanel getPanel() {
        return cardPanel;
    }
    
    protected void setup() {
        ImageIcon icon = Resource.getJarIcon("adminSplash.png");
        JLabel lbl = new JLabel("Runtime", icon, JLabel.CENTER);
        lbl.setFont(lbl.getFont().deriveFont(20.0f));
        lbl.setVerticalTextPosition(SwingConstants.TOP);
        lbl.setHorizontalTextPosition(SwingConstants.CENTER);
        cardPanel.add(lbl, CARD_Splash);
        cardLayout.show(cardPanel, CARD_Splash);
    
        getTree();
        OATreeTitleNode ttNode;
    
        // AppServers - App Server - 
        Hub<AppServer> hubAppServer = ModelDelegate.getCreateOneAppServerHub().createSharedHub();
        HubAODelegate.keepActiveObject(hubAppServer);  // createOne=true, auto set active object
        AppServerJfc jfcAppServer = new AppServerJfc(hubAppServer) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                RuntimeBarBase.this.cardLayout.show(RuntimeBarBase.this.cardPanel, CARD_AppServers);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = getCardPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating AppServerJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        RuntimeBarBase.this.cardPanel.add(panx, CARD_AppServers);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            protected void onShowListPanel() {
                super.onShowEditPanel();  // only one object, need to show editor
            }
        };
        jfcAppServer.getModel().setPluralDisplayName("App Server");
        jfcAppServer.getModel().setAllowAdd(false);
        jfcAppServer.getModel().setAllowDownload(true);
        jfcAppServer.getModel().setAllowRemove(false);
        jfcAppServer.getModel().setAllowSearch(false);
        // createOne=true
        jfcAppServer.getModel().setAllowDelete(false);
        jfcAppServer.getModel().setAllowClear(false);
        jfcAppServer.getModel().setAllowCut(false);
        jfcAppServer.getModel().setAllowPaste(false);
        jfcAppServer.getModel().setAllowGotoList(false);
        jfcAppServer.getModel().setAllowNew(false);
        ttNode = jfcAppServer.getTreeTitleNode();
        tree.add(ttNode);
        cardPanel.add(new JLabel("loading App Server ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_AppServers);
    
        // AppRuntimes - App Runtime - 
        Hub<AppRuntime> hubAppRuntime = ModelDelegate.getCreateOneAppRuntimeHub().createSharedHub();
        HubAODelegate.keepActiveObject(hubAppRuntime);  // createOne=true, auto set active object
        AppRuntimeJfc jfcAppRuntime = new AppRuntimeJfc(hubAppRuntime) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                RuntimeBarBase.this.cardLayout.show(RuntimeBarBase.this.cardPanel, CARD_AppRuntimes);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = getCardPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating AppRuntimeJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        RuntimeBarBase.this.cardPanel.add(panx, CARD_AppRuntimes);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            protected void onShowListPanel() {
                super.onShowEditPanel();  // only one object, need to show editor
            }
        };
        jfcAppRuntime.getModel().setPluralDisplayName("App Runtime");
        jfcAppRuntime.getModel().setAllowAdd(false);
        jfcAppRuntime.getModel().setAllowDownload(true);
        jfcAppRuntime.getModel().setAllowRemove(false);
        jfcAppRuntime.getModel().setAllowSearch(false);
        // createOne=true
        jfcAppRuntime.getModel().setAllowDelete(false);
        jfcAppRuntime.getModel().setAllowClear(false);
        jfcAppRuntime.getModel().setAllowCut(false);
        jfcAppRuntime.getModel().setAllowPaste(false);
        jfcAppRuntime.getModel().setAllowGotoList(false);
        jfcAppRuntime.getModel().setAllowNew(false);
        ttNode = jfcAppRuntime.getTreeTitleNode();
        tree.add(ttNode);
        cardPanel.add(new JLabel("loading App Runtime ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_AppRuntimes);
    
        // ConnectedAppUserLogins - Connected Users - 
        Hub<AppUserLogin> hubAppUserLogin = ModelDelegate.getConnectedAppUserLogins().createSharedHub();
        AppUserLoginJfc jfcAppUserLogin = new AppUserLoginJfc(hubAppUserLogin) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                RuntimeBarBase.this.cardLayout.show(RuntimeBarBase.this.cardPanel, CARD_ConnectedAppUserLogins);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = createCombinedPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating AppUserLoginJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        RuntimeBarBase.this.cardPanel.add(panx, CARD_ConnectedAppUserLogins);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            public OATable createTable() {
                OATable table = super.createTable();
                table.setPreferredRows(15);
                return table;
            }
        };
        jfcAppUserLogin.getModel().setPluralDisplayName("Connected Users");
        jfcAppUserLogin.getModel().setAllowAdd(false);
        jfcAppUserLogin.getModel().setAllowDownload(true);
        jfcAppUserLogin.getModel().setAllowRemove(false);
        jfcAppUserLogin.getModel().setAllowSearch(false);
        // AppUserLogin isProcessed=true
        // jfcAppUserLogin.getModel().setAllowDelete(false);
        jfcAppUserLogin.getModel().setAllowClear(false);
        jfcAppUserLogin.getModel().setAllowCut(false);
        jfcAppUserLogin.getModel().setAllowPaste(false);
        jfcAppUserLogin.getModel().setAllowNew(true);
        ttNode = jfcAppUserLogin.getTreeTitleNode();
        tree.add(ttNode);
        cardPanel.add(new JLabel("loading Connected Users ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_ConnectedAppUserLogins);
    
        // LastDayAppUserLogins - Last Day User Logins - 
        hubAppUserLogin = ModelDelegate.getLastDayAppUserLogins().createSharedHub();
        jfcAppUserLogin = new AppUserLoginJfc(hubAppUserLogin) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                RuntimeBarBase.this.cardLayout.show(RuntimeBarBase.this.cardPanel, CARD_LastDayAppUserLogins);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = createCombinedPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating AppUserLoginJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        RuntimeBarBase.this.cardPanel.add(panx, CARD_LastDayAppUserLogins);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            public OATable createTable() {
                OATable table = super.createTable();
                table.setPreferredRows(15);
                return table;
            }
        };
        jfcAppUserLogin.getModel().setPluralDisplayName("Last Day User Logins");
        jfcAppUserLogin.getModel().setAllowAdd(false);
        jfcAppUserLogin.getModel().setAllowDownload(true);
        jfcAppUserLogin.getModel().setAllowRemove(false);
        jfcAppUserLogin.getModel().setAllowSearch(false);
        // AppUserLogin isProcessed=true
        // jfcAppUserLogin.getModel().setAllowDelete(false);
        jfcAppUserLogin.getModel().setAllowClear(false);
        jfcAppUserLogin.getModel().setAllowCut(false);
        jfcAppUserLogin.getModel().setAllowPaste(false);
        jfcAppUserLogin.getModel().setAllowNew(true);
        ttNode = jfcAppUserLogin.getTreeTitleNode();
        tree.add(ttNode);
        cardPanel.add(new JLabel("loading Last Day User Logins ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_LastDayAppUserLogins);
    
        // AppUserErrors - User Errors - 
        Hub<AppUserError> hubAppUserError = ModelDelegate.getAppUserErrors().createSharedHub();
        AppUserErrorJfc jfcAppUserError = new AppUserErrorJfc(hubAppUserError) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                RuntimeBarBase.this.cardLayout.show(RuntimeBarBase.this.cardPanel, CARD_AppUserErrors);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = createCombinedPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating AppUserErrorJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        RuntimeBarBase.this.cardPanel.add(panx, CARD_AppUserErrors);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            public OATable createTable() {
                OATable table = super.createTable();
                table.setPreferredRows(15);
                return table;
            }
        };
        jfcAppUserError.getModel().setPluralDisplayName("User Errors");
        jfcAppUserError.getModel().setAllowAdd(false);
        jfcAppUserError.getModel().setAllowDownload(true);
        jfcAppUserError.getModel().setAllowRemove(false);
        jfcAppUserError.getModel().setAllowSearch(false);
        // AppUserError isProcessed=true
        // jfcAppUserError.getModel().setAllowDelete(false);
        jfcAppUserError.getModel().setAllowClear(false);
        jfcAppUserError.getModel().setAllowCut(false);
        jfcAppUserError.getModel().setAllowPaste(false);
        jfcAppUserError.getModel().setAllowNew(true);
        ttNode = jfcAppUserError.getTreeTitleNode();
        tree.add(ttNode);
        cardPanel.add(new JLabel("loading User Errors ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_AppUserErrors);
    }
    protected OATree getTree() {
        if (tree != null) return tree;
        tree = new OATree(18) {
            @Override
            public void nodeSelected(OATreeNode node) {
                super.nodeSelected(node);
                if (node == null) {
                    RuntimeBarBase.this.cardLayout.show(RuntimeBarBase.this.cardPanel, RuntimeBarBase.this.CARD_Splash);
                }
            }
        };
        tree.setAllowDnD(true);
        return tree;
    }
}

