// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.admin;

import java.util.logging.*;

public class RuntimeBar extends RuntimeBarBase {
    private static Logger LOG = Logger.getLogger(RuntimeBarBase.class.getName());
}
