// Generated by OABuilder
package com.viaoa.appstore.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.viaoa.util.OADateTime;
import com.viaoa.appstore.delegate.oa.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.ModelDelegate;
 
@OAClass(
    lowerName = "clientApp",
    pluralName = "ClientApps",
    shortName = "cla",
    displayName = "Client App",
    isProcessed = true,
    displayProperty = "serverApplication",
    noPojo = true
)
@OATable(
    indexes = {
        @OAIndex(name = "ClientAppAppUser", fkey = true, columns = { @OAIndexColumn(name = "AppUserId") }), 
        @OAIndex(name = "ClientAppRunningApp", fkey = true, columns = { @OAIndexColumn(name = "RunningAppId") }), 
        @OAIndex(name = "ClientAppServerApplication", fkey = true, columns = { @OAIndexColumn(name = "ServerApplicationId") })
    }
)
public class ClientApp extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(ClientApp.class.getName());

    public static final String P_Id = "id";
    public static final String P_Created = "created";
     
    public static final String P_AppUser = "appUser";
    public static final String P_AppUserId = "appUserId"; // fkey
    public static final String P_RunningApp = "runningApp";
    public static final String P_RunningAppId = "runningAppId"; // fkey
    public static final String P_ServerApplication = "serverApplication";
    public static final String P_ServerApplicationId = "serverApplicationId"; // fkey
     
    public static final String M_Run = "run";
    protected volatile int id;
    protected volatile OADateTime created;
     
    // Links to other objects.
    protected volatile transient AppUser appUser;
    protected volatile transient RunningApp runningApp;
    protected volatile transient ServerApplication serverApplication;
     
    public ClientApp() {
        if (!isLoading()) setObjectDefaults();
    }
    @Override
    public void setObjectDefaults() {
        setCreated(new OADateTime());
    }
     
    public ClientApp(int id) {
        this();
        setId(id);
    }

    @OAProperty(isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(defaultValue = "new OADateTime()", displayLength = 15, isProcessed = true)
    @OAColumn(name = "Created", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
    }

    @OAOne(
        displayName = "App User", 
        reverseName = AppUser.P_ClientApps, 
        required = true, 
        allowCreateNew = false, 
        defaultContextPropertyPath = ".", 
        fkeys = {@OAFkey(fromProperty = P_AppUserId, toProperty = AppUser.P_Id)}
    )
    public AppUser getAppUser() {
        if (appUser == null) {
            appUser = (AppUser) getObject(P_AppUser);
        }
        return appUser;
    }
    public void setAppUser(AppUser newValue) {
        AppUser old = this.appUser;
        fireBeforePropertyChange(P_AppUser, old, newValue);
        this.appUser = newValue;
        firePropertyChange(P_AppUser, old, this.appUser);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "AppUserId")
    public Integer getAppUserId() {
        return (Integer) getFkeyProperty(P_AppUserId);
    }
    public void setAppUserId(Integer newValue) {
        this.appUser = null;
        setFkeyProperty(P_AppUserId, newValue);
    }

    @OAOne(
        displayName = "Running App", 
        reverseName = RunningApp.P_ClientApp, 
        fkeys = {@OAFkey(fromProperty = P_RunningAppId, toProperty = RunningApp.P_Id)}
    )
    public RunningApp getRunningApp() {
        if (runningApp == null) {
            runningApp = (RunningApp) getObject(P_RunningApp);
        }
        return runningApp;
    }
    public void setRunningApp(RunningApp newValue) {
        RunningApp old = this.runningApp;
        fireBeforePropertyChange(P_RunningApp, old, newValue);
        this.runningApp = newValue;
        firePropertyChange(P_RunningApp, old, this.runningApp);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "RunningAppId")
    public Integer getRunningAppId() {
        return (Integer) getFkeyProperty(P_RunningAppId);
    }
    public void setRunningAppId(Integer newValue) {
        this.runningApp = null;
        setFkeyProperty(P_RunningAppId, newValue);
    }

    @OAOne(
        displayName = "Server Application", 
        reverseName = ServerApplication.P_ClientApps, 
        allowCreateNew = false, 
        selectFromPropertyPath = P_AppUser + "." + AppUser.P_MergeServerApplications, 
        fkeys = {@OAFkey(fromProperty = P_ServerApplicationId, toProperty = ServerApplication.P_Id)}
    )
    public ServerApplication getServerApplication() {
        if (serverApplication == null) {
            serverApplication = (ServerApplication) getObject(P_ServerApplication);
        }
        return serverApplication;
    }
    public void setServerApplication(ServerApplication newValue) {
        ServerApplication old = this.serverApplication;
        fireBeforePropertyChange(P_ServerApplication, old, newValue);
        this.serverApplication = newValue;
        firePropertyChange(P_ServerApplication, old, this.serverApplication);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "ServerApplicationId")
    public Integer getServerApplicationId() {
        return (Integer) getFkeyProperty(P_ServerApplicationId);
    }
    public void setServerApplicationId(Integer newValue) {
        this.serverApplication = null;
        setFkeyProperty(P_ServerApplicationId, newValue);
    }
    @OAMethod(displayName = "Run")
    public void run() throws Exception {
        // custom code
        ClientAppDelegate.run(this);
    }

    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        java.sql.Timestamp timestamp;
        timestamp = rs.getTimestamp(2);
        if (timestamp != null) this.created = new OADateTime(timestamp);
        int appUserFkey = rs.getInt(3);
        setFkeyProperty(P_AppUser, rs.wasNull() ? null : appUserFkey);
        int runningAppFkey = rs.getInt(4);
        setFkeyProperty(P_RunningApp, rs.wasNull() ? null : runningAppFkey);
        int serverApplicationFkey = rs.getInt(5);
        setFkeyProperty(P_ServerApplication, rs.wasNull() ? null : serverApplicationFkey);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
