// Generated by OABuilder
package com.viaoa.appstore.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.viaoa.util.OADateTime;
import com.viaoa.appstore.delegate.oa.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "serverApplication",
    pluralName = "ServerApplications",
    shortName = "sra",
    displayName = "Server Application",
    displayProperty = "displayName",
    noPojo = true,
    rootTreePropertyPaths = {
        "[ApplicationType]."+ApplicationType.P_ServerApplications, 
        "[Environment]."+Environment.P_MergeServerApplications, 
        "[Environment]."+Environment.P_Servers+"."+Server.P_ServerApplications
    }
)
@OATable(
    indexes = {
        @OAIndex(name = "ServerApplicationApplicationType", fkey = true, columns = { @OAIndexColumn(name = "ApplicationTypeId") }), 
        @OAIndex(name = "ServerApplicationApplicationVersion", fkey = true, columns = { @OAIndexColumn(name = "ApplicationVersionId") }), 
        @OAIndex(name = "ServerApplicationRunningApp", fkey = true, columns = { @OAIndexColumn(name = "RunningAppId") }), 
        @OAIndex(name = "ServerApplicationServer", fkey = true, columns = { @OAIndexColumn(name = "ServerId") })
    }
)
public class ServerApplication extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(ServerApplication.class.getName());

    public static final String P_Id = "id";
    public static final String P_Created = "created";
    public static final String P_ClientPort = "clientPort";
    public static final String P_HttpPort = "httpPort";
    public static final String P_HttpsPort = "httpsPort";
    public static final String P_CheckingVersion = "checkingVersion";
    public static final String P_LastConnect = "lastConnect";
     
    public static final String P_DisplayName = "displayName";
     
    public static final String P_ApplicationType = "applicationType";
    public static final String P_ApplicationTypeId = "applicationTypeId"; // fkey
    public static final String P_ApplicationVersion = "applicationVersion";
    public static final String P_ApplicationVersionId = "applicationVersionId"; // fkey
    public static final String P_ClientApps = "clientApps";
    public static final String P_MergeAppUsers = "mergeAppUsers";
    public static final String P_MergeEnvironment = "mergeEnvironment";
    public static final String P_RunningApp = "runningApp";
    public static final String P_RunningAppId = "runningAppId"; // fkey
    public static final String P_Server = "server";
    public static final String P_ServerId = "serverId"; // fkey
     
    public static final String M_Run = "run";
    protected volatile int id;
    protected volatile OADateTime created;
    protected volatile int clientPort;
    protected volatile int httpPort;
    protected volatile int httpsPort;
    protected volatile OADateTime checkingVersion;
    protected volatile OADateTime lastConnect;
     
    // Links to other objects.
    protected volatile transient ApplicationType applicationType;
    protected volatile transient ApplicationVersion applicationVersion;
    protected transient Hub<ClientApp> hubClientApps;
    protected volatile transient RunningApp runningApp;
    protected volatile transient Server server;
     
    public ServerApplication() {
        if (!isLoading()) setObjectDefaults();
    }
    @Override
    public void setObjectDefaults() {
        setCreated(new OADateTime());
    }
     
    public ServerApplication(int id) {
        this();
        setId(id);
    }

    @OAProperty(isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(defaultValue = "new OADateTime()", displayLength = 15, isProcessed = true)
    @OAColumn(name = "Created", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
    }

    @OAProperty(displayName = "Client Port", displayLength = 6, uiColumnLength = 11, format = "#")
    @OAColumn(name = "ClientPort", sqlType = java.sql.Types.INTEGER)
    public int getClientPort() {
        return clientPort;
    }
    public void setClientPort(int newValue) {
        int old = clientPort;
        fireBeforePropertyChange(P_ClientPort, old, newValue);
        this.clientPort = newValue;
        firePropertyChange(P_ClientPort, old, this.clientPort);
    }

    @OAProperty(displayName = "Http Port", displayLength = 6, uiColumnLength = 9, format = "#")
    @OAColumn(name = "HttpPort", sqlType = java.sql.Types.INTEGER)
    public int getHttpPort() {
        return httpPort;
    }
    public void setHttpPort(int newValue) {
        int old = httpPort;
        fireBeforePropertyChange(P_HttpPort, old, newValue);
        this.httpPort = newValue;
        firePropertyChange(P_HttpPort, old, this.httpPort);
    }

    @OAProperty(displayName = "Https Port", displayLength = 6, uiColumnLength = 10, format = "#")
    @OAColumn(name = "HttpsPort", sqlType = java.sql.Types.INTEGER)
    public int getHttpsPort() {
        return httpsPort;
    }
    public void setHttpsPort(int newValue) {
        int old = httpsPort;
        fireBeforePropertyChange(P_HttpsPort, old, newValue);
        this.httpsPort = newValue;
        firePropertyChange(P_HttpsPort, old, this.httpsPort);
    }

    @OAProperty(displayName = "Checking Version", displayLength = 15, uiColumnLength = 16, isProcessed = true)
    public OADateTime getCheckingVersion() {
        return checkingVersion;
    }
    public void setCheckingVersion(OADateTime newValue) {
        OADateTime old = checkingVersion;
        fireBeforePropertyChange(P_CheckingVersion, old, newValue);
        this.checkingVersion = newValue;
        firePropertyChange(P_CheckingVersion, old, this.checkingVersion);
    }

    @OAProperty(displayName = "Last Connect", displayLength = 15, isProcessed = true)
    @OAColumn(name = "LastConnect", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getLastConnect() {
        return lastConnect;
    }
    public void setLastConnect(OADateTime newValue) {
        OADateTime old = lastConnect;
        fireBeforePropertyChange(P_LastConnect, old, newValue);
        this.lastConnect = newValue;
        firePropertyChange(P_LastConnect, old, this.lastConnect);
    }
    @OACalculatedProperty(displayName = "Display Name", displayLength = 15, properties = {P_ApplicationType+"."+ApplicationType.P_Name, P_Server+"."+Server.P_Name, P_Server+"."+Server.P_Environment+"."+Environment.P_Name})
    public String getDisplayName() {
        String name = "";
        ApplicationType applicationType = this.getApplicationType();
        if (applicationType != null) {
            name = applicationType.getName();
        }
        Server server = getServer();
        if (server != null) {
            name += " (";
            Environment env = server.getEnvironment();
            if (env != null) name += env.getAbbrevName() + " ";
            name += server.getName() + ")";
        }
        return name;
    }

    @OAOne(
        displayName = "Application Type", 
        reverseName = ApplicationType.P_ServerApplications, 
        required = true, 
        allowCreateNew = false, 
        fkeys = {@OAFkey(fromProperty = P_ApplicationTypeId, toProperty = ApplicationType.P_Id)}
    )
    public ApplicationType getApplicationType() {
        if (applicationType == null) {
            applicationType = (ApplicationType) getObject(P_ApplicationType);
        }
        return applicationType;
    }
    public void setApplicationType(ApplicationType newValue) {
        ApplicationType old = this.applicationType;
        fireBeforePropertyChange(P_ApplicationType, old, newValue);
        this.applicationType = newValue;
        firePropertyChange(P_ApplicationType, old, this.applicationType);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "ApplicationTypeId")
    public Integer getApplicationTypeId() {
        return (Integer) getFkeyProperty(P_ApplicationTypeId);
    }
    public void setApplicationTypeId(Integer newValue) {
        this.applicationType = null;
        setFkeyProperty(P_ApplicationTypeId, newValue);
    }

    @OAOne(
        displayName = "Application Version", 
        reverseName = ApplicationVersion.P_ServerApplications, 
        allowCreateNew = false, 
        selectFromPropertyPath = P_ApplicationType + "." + ApplicationType.P_ApplicationVersions, 
        fkeys = {@OAFkey(fromProperty = P_ApplicationVersionId, toProperty = ApplicationVersion.P_Id)}
    )
    public ApplicationVersion getApplicationVersion() {
        if (applicationVersion == null) {
            applicationVersion = (ApplicationVersion) getObject(P_ApplicationVersion);
        }
        return applicationVersion;
    }
    public void setApplicationVersion(ApplicationVersion newValue) {
        ApplicationVersion old = this.applicationVersion;
        fireBeforePropertyChange(P_ApplicationVersion, old, newValue);
        this.applicationVersion = newValue;
        firePropertyChange(P_ApplicationVersion, old, this.applicationVersion);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "ApplicationVersionId")
    public Integer getApplicationVersionId() {
        return (Integer) getFkeyProperty(P_ApplicationVersionId);
    }
    public void setApplicationVersionId(Integer newValue) {
        this.applicationVersion = null;
        setFkeyProperty(P_ApplicationVersionId, newValue);
    }

    @OAMany(
        displayName = "Client Apps", 
        toClass = ClientApp.class, 
        reverseName = ClientApp.P_ServerApplication
    )
    public Hub<ClientApp> getClientApps() {
        if (hubClientApps == null) {
            hubClientApps = (Hub<ClientApp>) getHub(P_ClientApps);
        }
        return hubClientApps;
    }

    @OAMany(
        displayName = "App Users", 
        toClass = AppUser.class, 
        isCalculated = true, 
        reverseName = AppUser.P_MergeServerApplications, 
        createMethod = false
    )
    private Hub<AppUser> getMergeAppUsers() {
        // oamodel has createMethod set to false, this method exists only for annotations.
        return null;
    }

    @OAOne(
        displayName = "Environment", 
        isCalculated = true, 
        reverseName = Environment.P_MergeServerApplications, 
        allowCreateNew = false, 
        allowAddExisting = false
    )
    private Environment getMergeEnvironment() {
        // oamodel has createMethod set to false, this method exists only for annotations.
        return null;
    }

    @OAOne(
        displayName = "Running App", 
        reverseName = RunningApp.P_ServerApplication, 
        fkeys = {@OAFkey(fromProperty = P_RunningAppId, toProperty = RunningApp.P_Id)}
    )
    public RunningApp getRunningApp() {
        if (runningApp == null) {
            runningApp = (RunningApp) getObject(P_RunningApp);
        }
        return runningApp;
    }
    public void setRunningApp(RunningApp newValue) {
        RunningApp old = this.runningApp;
        fireBeforePropertyChange(P_RunningApp, old, newValue);
        this.runningApp = newValue;
        firePropertyChange(P_RunningApp, old, this.runningApp);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "RunningAppId")
    public Integer getRunningAppId() {
        return (Integer) getFkeyProperty(P_RunningAppId);
    }
    public void setRunningAppId(Integer newValue) {
        this.runningApp = null;
        setFkeyProperty(P_RunningAppId, newValue);
    }

    @OAOne(
        reverseName = Server.P_ServerApplications, 
        required = true, 
        allowCreateNew = false, 
        fkeys = {@OAFkey(fromProperty = P_ServerId, toProperty = Server.P_Id)}
    )
    public Server getServer() {
        if (server == null) {
            server = (Server) getObject(P_Server);
        }
        return server;
    }
    public void setServer(Server newValue) {
        Server old = this.server;
        fireBeforePropertyChange(P_Server, old, newValue);
        this.server = newValue;
        firePropertyChange(P_Server, old, this.server);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "ServerId")
    public Integer getServerId() {
        return (Integer) getFkeyProperty(P_ServerId);
    }
    public void setServerId(Integer newValue) {
        this.server = null;
        setFkeyProperty(P_ServerId, newValue);
    }
    @OAMethod(displayName = "Run")
    public void run() throws Exception {
        // custom code
        ServerApplicationDelegate.run(this);
    }

    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        java.sql.Timestamp timestamp;
        timestamp = rs.getTimestamp(2);
        if (timestamp != null) this.created = new OADateTime(timestamp);
        this.clientPort = rs.getInt(3);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_ClientPort, rs.wasNull());
        this.httpPort = rs.getInt(4);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_HttpPort, rs.wasNull());
        this.httpsPort = rs.getInt(5);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_HttpsPort, rs.wasNull());
        timestamp = rs.getTimestamp(6);
        if (timestamp != null) this.lastConnect = new OADateTime(timestamp);
        int applicationTypeFkey = rs.getInt(7);
        setFkeyProperty(P_ApplicationType, rs.wasNull() ? null : applicationTypeFkey);
        int applicationVersionFkey = rs.getInt(8);
        setFkeyProperty(P_ApplicationVersion, rs.wasNull() ? null : applicationVersionFkey);
        int runningAppFkey = rs.getInt(9);
        setFkeyProperty(P_RunningApp, rs.wasNull() ? null : runningAppFkey);
        int serverFkey = rs.getInt(10);
        setFkeyProperty(P_Server, rs.wasNull() ? null : serverFkey);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
