// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import com.viaoa.appstore.model.oa.*;
 
public class AppStoreServerPP {
    private static RunningAppPPx runningApp;
     

    public static RunningAppPPx runningApp() {
        if (runningApp == null) runningApp = new RunningAppPPx(AppStoreServer.P_RunningApp);
        return runningApp;
    }

    public static String id() {
        String s = AppStoreServer.P_Id;
        return s;
    }

    public static String created() {
        String s = AppStoreServer.P_Created;
        return s;
    }

    public static String name() {
        String s = AppStoreServer.P_Name;
        return s;
    }

    public static String server() {
        String s = AppStoreServer.P_Server;
        return s;
    }

    public static String console() {
        String s = AppStoreServer.P_Console;
        return s;
    }

    public static String run() {
        String s = "run";
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
