// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.envs;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.*;
import javax.swing.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;

public class EnvironmentsBarBase {
    private static Logger LOG = Logger.getLogger(EnvironmentsBarBase.class.getName());
    
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    protected OATree tree;
    
    public static final String CARD_Splash = "splash";
    public static final String CARD_Environments = "Environments";
    
    public EnvironmentsBarBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        setup();
    }
    
    public JPanel getPanel() {
        return cardPanel;
    }
    
    protected void setup() {
        ImageIcon icon = Resource.getJarIcon("envsSplash.png");
        JLabel lbl = new JLabel("Environments", icon, JLabel.CENTER);
        lbl.setFont(lbl.getFont().deriveFont(20.0f));
        lbl.setVerticalTextPosition(SwingConstants.TOP);
        lbl.setHorizontalTextPosition(SwingConstants.CENTER);
        cardPanel.add(lbl, CARD_Splash);
        cardLayout.show(cardPanel, CARD_Splash);
    
        getTree();
        OATreeTitleNode ttNode;
    
        // Environments - Environments - 
        Hub<Environment> hubEnvironment = ModelDelegate.getEnvironments().createSharedHub();
        EnvironmentJfc jfcEnvironment = new EnvironmentJfc(hubEnvironment) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                EnvironmentsBarBase.this.cardLayout.show(EnvironmentsBarBase.this.cardPanel, CARD_Environments);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = getCardPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating EnvironmentJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        EnvironmentsBarBase.this.cardPanel.add(panx, CARD_Environments);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            public OATable createTable() {
                OATable table = super.createTable();
                table.setPreferredRows(15);
                return table;
            }
        };
        jfcEnvironment.getModel().setPluralDisplayName("Environments");
        jfcEnvironment.getModel().setAllowAdd(false);
        jfcEnvironment.getModel().setAllowDownload(true);
        jfcEnvironment.getModel().setAllowRemove(false);
        jfcEnvironment.getModel().setAllowSearch(false);
        jfcEnvironment.getModel().setAllowHubSearch(true);
        jfcEnvironment.getModel().setAllowNew(true);
        jfcEnvironment.getModel().setAllowMove(true);
        jfcEnvironment.getModel().setAllowTableFilter(false); // a table cant have filtered and move at same time
        ttNode = jfcEnvironment.getTreeTitleNode();
        tree.add(ttNode);
        ttNode.add(jfcEnvironment.getTreeNode());
        cardPanel.add(new JLabel("loading Environments ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_Environments);
    }
    protected OATree getTree() {
        if (tree != null) return tree;
        tree = new OATree(18) {
            @Override
            public void nodeSelected(OATreeNode node) {
                super.nodeSelected(node);
                if (node == null) {
                    EnvironmentsBarBase.this.cardLayout.show(EnvironmentsBarBase.this.cardPanel, EnvironmentsBarBase.this.CARD_Splash);
                }
            }
        };
        tree.setAllowDnD(true);
        return tree;
    }
}

