// Generated by OABuilder 03/03/24 06:30 AM

package com.viaoa.appstore.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.*;
import com.viaoa.appstore.delegate.oa.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.*;

public class AppRuntimeJfc extends AppRuntimeJfcBase {
    
    public AppRuntimeJfc() {
    }
    
    public AppRuntimeJfc(Hub<AppRuntime> hubAppRuntime) {
        super(hubAppRuntime);
    }
    
    public AppRuntimeJfc(AppRuntimeModel modelAppRuntime) {
        super(modelAppRuntime);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

