// Generated by OABuilder 03/26/24 01:48 PM

package com.viaoa.appstore.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.*;
import com.viaoa.appstore.delegate.oa.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.*;

public class ClientAppJfc extends ClientAppJfcBase {
    
    public ClientAppJfc() {
    }
    
    public ClientAppJfc(Hub<ClientApp> hubClientApp) {
        super(hubClientApp);
    }
    
    public ClientAppJfc(ClientAppModel modelClientApp) {
        super(modelClientApp);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

