// Generated by OABuilder 04/28/24 07:33 PM

package com.viaoa.appstore.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.*;
import com.viaoa.appstore.delegate.oa.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.*;

public class PropertyValueJfc extends PropertyValueJfcBase {
    
    public PropertyValueJfc() {
    }
    
    public PropertyValueJfc(Hub<PropertyValue> hubPropertyValue) {
        super(hubPropertyValue);
    }
    
    public PropertyValueJfc(PropertyValueModel modelPropertyValue) {
        super(modelPropertyValue);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

