// Generated by OABuilder 03/26/24 02:05 PM

package com.viaoa.appstore.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.delegate.*;
import com.viaoa.appstore.delegate.oa.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.*;

public class SingleAppJfc extends SingleAppJfcBase {
    
    public SingleAppJfc() {
    }
    
    public SingleAppJfc(Hub<SingleApp> hubSingleApp) {
        super(hubSingleApp);
    }
    
    public SingleAppJfc(SingleAppModel modelSingleApp) {
        super(modelSingleApp);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

