// Generated by OABuilder
package com.viaoa.appstore.model.filter;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class ApplicationVersionLastDayFilterModel {
    private static Logger LOG = Logger.getLogger(ApplicationVersionLastDayFilterModel.class.getName());
    
    // Hubs
    protected Hub<ApplicationVersionLastDayFilter> hubFilter;
    
    // ObjectModels
    
    // object used for filter data
    protected ApplicationVersionLastDayFilter filter;
    
    public ApplicationVersionLastDayFilterModel(Hub<ApplicationVersion> hubMaster, Hub<ApplicationVersion> hub) {
        filter = new ApplicationVersionLastDayFilter(hubMaster, hub);
    }
    public ApplicationVersionLastDayFilterModel(Hub<ApplicationVersion> hub) {
        filter = new ApplicationVersionLastDayFilter(hub);
    }
    
    // object used to input query data, to be used by filterHub
    public ApplicationVersionLastDayFilter getFilter() {
        return filter;
    }
    
    // hub for filter UI object - used to bind with UI components for entering filter data
    public Hub<ApplicationVersionLastDayFilter> getFilterHub() {
        if (hubFilter == null) {
            hubFilter = new Hub<ApplicationVersionLastDayFilter>(ApplicationVersionLastDayFilter.class);
            hubFilter.add(getFilter());
            hubFilter.setPos(0);
        }
        return hubFilter;
    }
    
    
    
    // get the Filtered hub
    public Hub<ApplicationVersion> getHub() {
        return getFilter().getHubFilter().getHub();
    }
}

