// Generated by OABuilder
package com.viaoa.appstore.model.filter;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class AppRuntimeErrorOpenFilterModel {
    private static Logger LOG = Logger.getLogger(AppRuntimeErrorOpenFilterModel.class.getName());
    
    // Hubs
    protected Hub<AppRuntimeErrorOpenFilter> hubFilter;
    
    // ObjectModels
    
    // object used for filter data
    protected AppRuntimeErrorOpenFilter filter;
    
    public AppRuntimeErrorOpenFilterModel(Hub<AppRuntimeError> hubMaster, Hub<AppRuntimeError> hub) {
        filter = new AppRuntimeErrorOpenFilter(hubMaster, hub);
    }
    public AppRuntimeErrorOpenFilterModel(Hub<AppRuntimeError> hub) {
        filter = new AppRuntimeErrorOpenFilter(hub);
    }
    
    // object used to input query data, to be used by filterHub
    public AppRuntimeErrorOpenFilter getFilter() {
        return filter;
    }
    
    // hub for filter UI object - used to bind with UI components for entering filter data
    public Hub<AppRuntimeErrorOpenFilter> getFilterHub() {
        if (hubFilter == null) {
            hubFilter = new Hub<AppRuntimeErrorOpenFilter>(AppRuntimeErrorOpenFilter.class);
            hubFilter.add(getFilter());
            hubFilter.setPos(0);
        }
        return hubFilter;
    }
    
    
    
    // get the Filtered hub
    public Hub<AppRuntimeError> getHub() {
        return getFilter().getHubFilter().getHub();
    }
}

