// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.application;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.*;
import javax.swing.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;

public class AppStoreServersBarBase {
    private static Logger LOG = Logger.getLogger(AppStoreServersBarBase.class.getName());
    
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    protected OATree tree;
    
    public static final String CARD_Splash = "splash";
    public static final String CARD_AppStoreServers1 = "AppStoreServers1";
    
    public AppStoreServersBarBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        setup();
    }
    
    public JPanel getPanel() {
        return cardPanel;
    }
    
    protected void setup() {
        ImageIcon icon = Resource.getJarIcon("appStoreServersSplash.png");
        JLabel lbl = new JLabel("AppStore Servers", icon, JLabel.CENTER);
        lbl.setFont(lbl.getFont().deriveFont(20.0f));
        lbl.setVerticalTextPosition(SwingConstants.TOP);
        lbl.setHorizontalTextPosition(SwingConstants.CENTER);
        cardPanel.add(lbl, CARD_Splash);
        cardLayout.show(cardPanel, CARD_Splash);
    
        getTree();
        OATreeTitleNode ttNode;
    
        // AppStoreServers1 - AppStoreServers - 
        Hub<AppStoreServer> hubAppStoreServer = ModelDelegate.getAppStoreServers().createSharedHub();
        AppStoreServerJfc jfcAppStoreServer = new AppStoreServerJfc(hubAppStoreServer) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                AppStoreServersBarBase.this.cardLayout.show(AppStoreServersBarBase.this.cardPanel, CARD_AppStoreServers1);
                if (panx != null) {
                    super.showCardPanel(name);
                    return;
                }
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = getCardPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating AppStoreServerJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        AppStoreServersBarBase.this.cardPanel.add(panx, CARD_AppStoreServers1);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
            @Override
            public OATable createTable() {
                OATable table = super.createTable();
                table.setPreferredRows(15);
                return table;
            }
        };
        jfcAppStoreServer.getModel().setPluralDisplayName("AppStoreServers");
        jfcAppStoreServer.getModel().setAllowAdd(false);
        jfcAppStoreServer.getModel().setAllowDownload(true);
        jfcAppStoreServer.getModel().setAllowRemove(false);
        jfcAppStoreServer.getModel().setAllowSearch(false);
        jfcAppStoreServer.getModel().setAllowNew(true);
        ttNode = jfcAppStoreServer.getTreeTitleNode();
        tree.add(ttNode);
        ttNode.add(jfcAppStoreServer.getTreeNode());
        cardPanel.add(new JLabel("loading AppStoreServers ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_AppStoreServers1);
    }
    protected OATree getTree() {
        if (tree != null) return tree;
        tree = new OATree(18) {
            @Override
            public void nodeSelected(OATreeNode node) {
                super.nodeSelected(node);
                if (node == null) {
                    AppStoreServersBarBase.this.cardLayout.show(AppStoreServersBarBase.this.cardPanel, AppStoreServersBarBase.this.CARD_Splash);
                }
            }
        };
        tree.setAllowDnD(true);
        return tree;
    }
}

