// Generated by OABuilder
package com.viaoa.appstore.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class ApplicationTypeModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(ApplicationTypeModel.class.getName());
    
    // Hubs
    protected Hub<ApplicationType> hub;
    // selected applicationTypes
    protected Hub<ApplicationType> hubMultiSelect;
    // wizard HubNewObject
    protected HubNewObject hubNewObjectWizard;
    // detail hubs
    protected Hub<ApplicationVersion> hubApplicationVersions;
    protected Hub<AppUser> hubAppUsers;
    protected Hub<PropertyValue> hubPropertyValues;
    protected Hub<ServerApplication> hubServerApplications;
    
    // selectFrom
    protected Hub<AppUser> hubAppUsersSelectFrom;
    
    // ObjectModels
    protected ApplicationVersionModel modelApplicationVersions;
    protected AppUserModel modelAppUsers;
    protected PropertyValueModel modelPropertyValues;
    protected ServerApplicationModel modelServerApplications;
    
    // selectFrom
    protected AppUserModel modelAppUsersSelectFrom;
    
    // SearchModels used for references
    protected ApplicationVersionSearchModel modelApplicationVersionsSearch;
    protected AppUserSearchModel modelAppUsersSearch;
    protected PropertyValueSearchModel modelPropertyValuesSearch;
    protected ServerApplicationSearchModel modelServerApplicationsSearch;
    
    public ApplicationTypeModel() {
        setDisplayName("Application Type");
        setPluralDisplayName("Application Types");
    }
    
    public ApplicationTypeModel(Hub<ApplicationType> hubApplicationType) {
        this();
        if (hubApplicationType != null) HubDelegate.setObjectClass(hubApplicationType, ApplicationType.class);
        this.hub = hubApplicationType;
    }
    public ApplicationTypeModel(ApplicationType applicationType) {
        this();
        getHub().add(applicationType);
        getHub().setPos(0);
    }
    
    public Hub<ApplicationType> getOriginalHub() {
        return getHub();
    }
    
    public Hub<ApplicationVersion> getApplicationVersions() {
        if (hubApplicationVersions == null) {
            hubApplicationVersions = getHub().getDetailHub(ApplicationType.P_ApplicationVersions);
        }
        return hubApplicationVersions;
    }
    public Hub<AppUser> getAppUsers() {
        if (hubAppUsers == null) {
            hubAppUsers = getHub().getDetailHub(ApplicationType.P_AppUsers);
        }
        return hubAppUsers;
    }
    public Hub<PropertyValue> getPropertyValues() {
        if (hubPropertyValues == null) {
            hubPropertyValues = getHub().getDetailHub(ApplicationType.P_PropertyValues);
        }
        return hubPropertyValues;
    }
    public Hub<ServerApplication> getServerApplications() {
        if (hubServerApplications == null) {
            hubServerApplications = getHub().getDetailHub(ApplicationType.P_ServerApplications);
        }
        return hubServerApplications;
    }
    public Hub<AppUser> getAppUsersSelectFromHub() {
        if (hubAppUsersSelectFrom != null) return hubAppUsersSelectFrom;
        hubAppUsersSelectFrom = ModelDelegate.getAppUsers().createSharedHub();
        return hubAppUsersSelectFrom;
    }
    public ApplicationType getApplicationType() {
        return getHub().getAO();
    }
    
    public Hub<ApplicationType> getHub() {
        if (hub == null) {
            hub = new Hub<ApplicationType>(ApplicationType.class);
        }
        return hub;
    }
    
    public Hub<ApplicationType> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<ApplicationType>(ApplicationType.class);
        }
        return hubMultiSelect;
    }
    public Hub<ApplicationType> getWizardHub() {
        return getWizardHubNewObject().getNewObjectHub();
    }
    public HubNewObject<ApplicationType> getWizardHubNewObject() {
        if (hubNewObjectWizard == null) {
            hubNewObjectWizard = new HubNewObject(getHub());
        }
        return hubNewObjectWizard;
    }
    
    public ApplicationVersionModel getApplicationVersionsModel() {
        if (modelApplicationVersions != null) return modelApplicationVersions;
        modelApplicationVersions = new ApplicationVersionModel(getApplicationVersions());
        modelApplicationVersions.setDisplayName("Application Version");
        modelApplicationVersions.setPluralDisplayName("Application Versions");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getApplicationVersions())) {
            modelApplicationVersions.setCreateUI(false);
        }
        modelApplicationVersions.setForJfc(getForJfc());
        modelApplicationVersions.setAllowNew(false);
        modelApplicationVersions.setAllowSave(true);
        modelApplicationVersions.setAllowAdd(false);
        modelApplicationVersions.setAllowMove(false);
        modelApplicationVersions.setAllowRemove(false);
        modelApplicationVersions.setAllowDelete(true);
        modelApplicationVersions.setAllowRefresh(false);
        modelApplicationVersions.setAllowSearch(false);
        modelApplicationVersions.setAllowHubSearch(true);
        modelApplicationVersions.setAllowDownload(true);
        modelApplicationVersions.setAllowGotoEdit(true);
        modelApplicationVersions.setViewOnly(getViewOnly());
        modelApplicationVersions.setAllowTableFilter(true);
        modelApplicationVersions.setAllowTableSorting(true);
        modelApplicationVersions.setAllowMultiSelect(false);
        modelApplicationVersions.setAllowCopy(false);
        modelApplicationVersions.setAllowCut(false);
        modelApplicationVersions.setAllowPaste(false);
        // call ApplicationType.applicationVersionsModelCallback(ApplicationVersionModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ApplicationType.class, ApplicationType.P_ApplicationVersions, modelApplicationVersions);
    
        return modelApplicationVersions;
    }
    public AppUserModel getAppUsersModel() {
        if (modelAppUsers != null) return modelAppUsers;
        modelAppUsers = new AppUserModel(getAppUsers());
        modelAppUsers.setDisplayName("App User");
        modelAppUsers.setPluralDisplayName("App Users");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getAppUsers())) {
            modelAppUsers.setCreateUI(false);
        }
        modelAppUsers.setForJfc(getForJfc());
        modelAppUsers.setAllowNew(false);
        modelAppUsers.setAllowSave(true);
        modelAppUsers.setAllowAdd(true);
        modelAppUsers.setAllowMove(false);
        modelAppUsers.setAllowRemove(true);
        modelAppUsers.setAllowDelete(false);
        modelAppUsers.setAllowRefresh(false);
        modelAppUsers.setAllowSearch(false);
        modelAppUsers.setAllowHubSearch(true);
        modelAppUsers.setAllowDownload(true);
        modelAppUsers.setAllowGotoEdit(false);
        modelAppUsers.setViewOnly(getViewOnly());
        modelAppUsers.setAllowTableFilter(true);
        modelAppUsers.setAllowTableSorting(true);
        modelAppUsers.setAllowMultiSelect(false);
        modelAppUsers.setAllowCopy(false);
        modelAppUsers.setAllowCut(false);
        modelAppUsers.setAllowPaste(false);
        // call ApplicationType.appUsersModelCallback(AppUserModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ApplicationType.class, ApplicationType.P_AppUsers, modelAppUsers);
    
        return modelAppUsers;
    }
    public PropertyValueModel getPropertyValuesModel() {
        if (modelPropertyValues != null) return modelPropertyValues;
        modelPropertyValues = new PropertyValueModel(getPropertyValues());
        modelPropertyValues.setDisplayName("Property Value");
        modelPropertyValues.setPluralDisplayName("Property Values");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getPropertyValues())) {
            modelPropertyValues.setCreateUI(false);
        }
        modelPropertyValues.setForJfc(getForJfc());
        modelPropertyValues.setAllowNew(true);
        modelPropertyValues.setAllowSave(true);
        modelPropertyValues.setAllowAdd(true);
        modelPropertyValues.setAllowMove(false);
        modelPropertyValues.setAllowRemove(true);
        modelPropertyValues.setAllowDelete(false);
        modelPropertyValues.setAllowRefresh(false);
        modelPropertyValues.setAllowSearch(false);
        modelPropertyValues.setAllowHubSearch(false);
        modelPropertyValues.setAllowDownload(true);
        modelPropertyValues.setAllowGotoEdit(true);
        modelPropertyValues.setViewOnly(getViewOnly());
        modelPropertyValues.setAllowTableFilter(true);
        modelPropertyValues.setAllowTableSorting(true);
        modelPropertyValues.setAllowMultiSelect(false);
        modelPropertyValues.setAllowCopy(false);
        modelPropertyValues.setAllowCut(false);
        modelPropertyValues.setAllowPaste(false);
        // call ApplicationType.propertyValuesModelCallback(PropertyValueModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ApplicationType.class, ApplicationType.P_PropertyValues, modelPropertyValues);
    
        return modelPropertyValues;
    }
    public ServerApplicationModel getServerApplicationsModel() {
        if (modelServerApplications != null) return modelServerApplications;
        modelServerApplications = new ServerApplicationModel(getServerApplications());
        modelServerApplications.setDisplayName("Server Application");
        modelServerApplications.setPluralDisplayName("Server Applications");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getServerApplications())) {
            modelServerApplications.setCreateUI(false);
        }
        modelServerApplications.setForJfc(getForJfc());
        modelServerApplications.setAllowNew(false);
        modelServerApplications.setAllowSave(true);
        modelServerApplications.setAllowAdd(false);
        modelServerApplications.setAllowMove(false);
        modelServerApplications.setAllowRemove(false);
        modelServerApplications.setAllowDelete(true);
        modelServerApplications.setAllowRefresh(false);
        modelServerApplications.setAllowSearch(false);
        modelServerApplications.setAllowHubSearch(true);
        modelServerApplications.setAllowDownload(true);
        modelServerApplications.setAllowGotoEdit(true);
        modelServerApplications.setViewOnly(getViewOnly());
        modelServerApplications.setAllowTableFilter(true);
        modelServerApplications.setAllowTableSorting(true);
        modelServerApplications.setAllowMultiSelect(false);
        modelServerApplications.setAllowCopy(false);
        modelServerApplications.setAllowCut(false);
        modelServerApplications.setAllowPaste(false);
        // call ApplicationType.serverApplicationsModelCallback(ServerApplicationModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ApplicationType.class, ApplicationType.P_ServerApplications, modelServerApplications);
    
        return modelServerApplications;
    }
    
    public AppUserModel getAppUsersSelectFromModel() {
        if (modelAppUsersSelectFrom != null) return modelAppUsersSelectFrom;
        modelAppUsersSelectFrom = new AppUserModel(getAppUsersSelectFromHub());
        modelAppUsersSelectFrom.setDisplayName("App User");
        modelAppUsersSelectFrom.setPluralDisplayName("App Users");
        modelAppUsersSelectFrom.setForJfc(getForJfc());
        modelAppUsersSelectFrom.setAllowNew(false);
        modelAppUsersSelectFrom.setAllowSave(true);
        modelAppUsersSelectFrom.setAllowAdd(false);
        modelAppUsersSelectFrom.setAllowMove(false);
        modelAppUsersSelectFrom.setAllowRemove(false);
        modelAppUsersSelectFrom.setAllowDelete(false);
        modelAppUsersSelectFrom.setAllowRefresh(false);
        modelAppUsersSelectFrom.setAllowSearch(true);
        modelAppUsersSelectFrom.setAllowHubSearch(true);
        modelAppUsersSelectFrom.setAllowGotoEdit(true);
        modelAppUsersSelectFrom.setViewOnly(getViewOnly());
        modelAppUsersSelectFrom.setAllowNew(false);
        modelAppUsersSelectFrom.setAllowTableFilter(true);
        modelAppUsersSelectFrom.setAllowTableSorting(true);
        modelAppUsersSelectFrom.setAllowCut(false);
        modelAppUsersSelectFrom.setAllowCopy(false);
        modelAppUsersSelectFrom.setAllowPaste(false);
        modelAppUsersSelectFrom.setAllowMultiSelect(true);
        new HubMakeCopy(getAppUsers(), modelAppUsersSelectFrom.getMultiSelectHub());
        return modelAppUsersSelectFrom;
    }
    public ApplicationVersionSearchModel getApplicationVersionsSearchModel() {
        if (modelApplicationVersionsSearch != null) return modelApplicationVersionsSearch;
        modelApplicationVersionsSearch = new ApplicationVersionSearchModel();
        return modelApplicationVersionsSearch;
    }
    public AppUserSearchModel getAppUsersSearchModel() {
        if (modelAppUsersSearch != null) return modelAppUsersSearch;
        modelAppUsersSearch = new AppUserSearchModel();
        return modelAppUsersSearch;
    }
    public PropertyValueSearchModel getPropertyValuesSearchModel() {
        if (modelPropertyValuesSearch != null) return modelPropertyValuesSearch;
        modelPropertyValuesSearch = new PropertyValueSearchModel();
        return modelPropertyValuesSearch;
    }
    public ServerApplicationSearchModel getServerApplicationsSearchModel() {
        if (modelServerApplicationsSearch != null) return modelServerApplicationsSearch;
        modelServerApplicationsSearch = new ServerApplicationSearchModel();
        return modelServerApplicationsSearch;
    }
    
    public HubCopy<ApplicationType> createHubCopy() {
        Hub<ApplicationType> hubApplicationTypex = new Hub<>(ApplicationType.class);
        HubCopy<ApplicationType> hc = new HubCopy<>(getHub(), hubApplicationTypex, true);
        return hc;
    }
    public ApplicationTypeModel createCopy() {
        ApplicationTypeModel mod = new ApplicationTypeModel(createHubCopy().getHub());
        return mod;
    }
}

