// Generated by OABuilder
package com.viaoa.appstore.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class AppRuntimeErrorModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(AppRuntimeErrorModel.class.getName());
    
    /* overview
      originalHub   - save the original hub
      <- unfilteredHub - points one of the above hubs
      openFilteredHub;
      <- hub - points to unfiltered or filtered hub
    */
    
    // Hubs
    protected Hub<AppRuntimeError> hubOriginal;
    
    // base hub that points to one of: hubOriginal
    protected Hub<AppRuntimeError> hubUnfiltered;
    protected Hub<AppRuntimeError> hubOpenFilteredHub;
    // main hub that points to hubUnfiltered, hubOpenFilteredHub
    protected Hub<AppRuntimeError> hub;
    // selected appRuntimeErrors
    protected Hub<AppRuntimeError> hubMultiSelect;
    // detail hubs
    protected Hub<AppRuntime> hubAppRuntime;
    
    // AddHubs used for references
    protected Hub<AppRuntime> hubAppRuntimeSelectFrom;
    
    // ObjectModels
    protected AppRuntimeModel modelAppRuntime;
    
    // selectFrom
    protected AppRuntimeModel modelAppRuntimeSelectFrom;
    
    // SearchModels used for references
    protected AppRuntimeSearchModel modelAppRuntimeSearch;
    
    // FilterModels
    protected AppRuntimeErrorOpenFilterModel modelAppRuntimeErrorOpenFilter;
    
    public AppRuntimeErrorModel() {
        setDisplayName("App Runtime Error");
        setPluralDisplayName("App Runtime Errors");
    }
    
    public AppRuntimeErrorModel(Hub<AppRuntimeError> hubAppRuntimeError) {
        this();
        if (hubAppRuntimeError != null) HubDelegate.setObjectClass(hubAppRuntimeError, AppRuntimeError.class);
        this.hubOriginal = hubAppRuntimeError;
    }
    public AppRuntimeErrorModel(AppRuntimeError appRuntimeError) {
        this();
        getHub().add(appRuntimeError);
        getHub().setPos(0);
    }
    
    public void useUnfilteredHub() {
        getHub().setSharedHub(getUnfilteredHub(), true);
    }
    public void useOpenFilteredHub() {
        getHub().setSharedHub(getOpenFilteredHub(), true);
    }
    
    public Hub<AppRuntimeError> getOriginalHub() {
        if (hubOriginal == null) {
            hubOriginal = new Hub<AppRuntimeError>(AppRuntimeError.class);
        }
        return hubOriginal;
    }
    
    public Hub<AppRuntime> getAppRuntimeHub() {
        if (hubAppRuntime != null) return hubAppRuntime;
        // this is the owner, use detailHub
        hubAppRuntime = getHub().getDetailHub(AppRuntimeError.P_AppRuntime);
        return hubAppRuntime;
    }
    public Hub<AppRuntime> getAppRuntimeSelectFromHub() {
        if (hubAppRuntimeSelectFrom != null) return hubAppRuntimeSelectFrom;
        hubAppRuntimeSelectFrom = new Hub<AppRuntime>(AppRuntime.class);
        Hub<AppRuntime> hubAppRuntimeSelectFrom1 = ModelDelegate.getCreateOneAppRuntimeHub().createSharedHub();
        HubCombined<AppRuntime> hubCombined = new HubCombined(hubAppRuntimeSelectFrom, hubAppRuntimeSelectFrom1, getAppRuntimeHub());
        hubAppRuntimeSelectFrom.setLinkHub(getHub(), AppRuntimeError.P_AppRuntime); 
        return hubAppRuntimeSelectFrom;
    }
    public Hub<AppRuntimeError> getUnfilteredHub() {
        if (hubUnfiltered == null) {
            hubUnfiltered = new Hub<AppRuntimeError>(AppRuntimeError.class);
            hubUnfiltered.setSharedHub(getOriginalHub(), true);
        }
        return hubUnfiltered;
    }
    public Hub<AppRuntimeError> getOpenFilteredHub() {
        if (hubOpenFilteredHub == null) {
            hubOpenFilteredHub = new Hub<AppRuntimeError>(AppRuntimeError.class);
        }
        return hubOpenFilteredHub;
    }
    
    public AppRuntimeError getAppRuntimeError() {
        return getHub().getAO();
    }
    
    // points to filtered or unfiltered hub
    public Hub<AppRuntimeError> getHub() {
        if (hub == null) {
            hub = new Hub<AppRuntimeError>(AppRuntimeError.class);
            hub.setSharedHub(getUnfilteredHub(), true);
        }
        return hub;
    }
    
    public Hub<AppRuntimeError> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<AppRuntimeError>(AppRuntimeError.class);
        }
        return hubMultiSelect;
    }
    
    public AppRuntimeModel getAppRuntimeModel() {
        if (modelAppRuntime != null) return modelAppRuntime;
        modelAppRuntime = new AppRuntimeModel(getAppRuntimeHub());
        modelAppRuntime.setDisplayName("App Runtime");
        modelAppRuntime.setPluralDisplayName("App Runtimes");
        modelAppRuntime.setForJfc(getForJfc());
        modelAppRuntime.setAllowNew(false);
        modelAppRuntime.setAllowSave(true);
        modelAppRuntime.setAllowAdd(false);
        modelAppRuntime.setAllowRemove(false);
        modelAppRuntime.setAllowClear(false);
        modelAppRuntime.setAllowDelete(false);
        modelAppRuntime.setAllowSearch(false);
        modelAppRuntime.setAllowHubSearch(true);
        modelAppRuntime.setAllowGotoEdit(false);
        OALinkInfo li = HubDetailDelegate.getLinkInfoFromDetailToMaster(getOriginalHub());
        modelAppRuntime.setCreateUI(li == null || !AppRuntimeError.P_AppRuntime.equalsIgnoreCase(li.getName()) );
        modelAppRuntime.setViewOnly(getViewOnly());
        // call AppRuntimeError.appRuntimeModelCallback(AppRuntimeModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(AppRuntimeError.class, AppRuntimeError.P_AppRuntime, modelAppRuntime);
    
        return modelAppRuntime;
    }
    
    public AppRuntimeModel getAppRuntimeSelectFromModel() {
        if (modelAppRuntimeSelectFrom != null) return modelAppRuntimeSelectFrom;
        modelAppRuntimeSelectFrom = new AppRuntimeModel(getAppRuntimeSelectFromHub());
        modelAppRuntimeSelectFrom.setDisplayName("App Runtime");
        modelAppRuntimeSelectFrom.setPluralDisplayName("App Runtimes");
        modelAppRuntimeSelectFrom.setForJfc(getForJfc());
        modelAppRuntimeSelectFrom.setAllowNew(false);
        modelAppRuntimeSelectFrom.setAllowSave(true);
        modelAppRuntimeSelectFrom.setAllowAdd(false);
        modelAppRuntimeSelectFrom.setAllowMove(false);
        modelAppRuntimeSelectFrom.setAllowRemove(false);
        modelAppRuntimeSelectFrom.setAllowDelete(false);
        modelAppRuntimeSelectFrom.setAllowSearch(false);
        modelAppRuntimeSelectFrom.setAllowHubSearch(true);
        modelAppRuntimeSelectFrom.setAllowGotoEdit(true);
        modelAppRuntimeSelectFrom.setViewOnly(getViewOnly());
        modelAppRuntimeSelectFrom.setAllowNew(false);
        modelAppRuntimeSelectFrom.setAllowTableFilter(true);
        modelAppRuntimeSelectFrom.setAllowTableSorting(true);
        modelAppRuntimeSelectFrom.setAllowCut(false);
        modelAppRuntimeSelectFrom.setAllowCopy(false);
        modelAppRuntimeSelectFrom.setAllowPaste(false);
        modelAppRuntimeSelectFrom.setAllowMultiSelect(false);
        return modelAppRuntimeSelectFrom;
    }
    public AppRuntimeSearchModel getAppRuntimeSearchModel() {
        if (modelAppRuntimeSearch != null) return modelAppRuntimeSearch;
        modelAppRuntimeSearch = new AppRuntimeSearchModel();
        HubSelectDelegate.adoptWhereHub(modelAppRuntimeSearch.getHub(), AppRuntimeError.P_AppRuntime, getHub());
        return modelAppRuntimeSearch;
    }
    
    public AppRuntimeErrorOpenFilterModel getAppRuntimeErrorOpenFilterModel() {
        if (modelAppRuntimeErrorOpenFilter == null) {
            modelAppRuntimeErrorOpenFilter = new AppRuntimeErrorOpenFilterModel(getUnfilteredHub(), getOpenFilteredHub());
            new HubShareAO(getUnfilteredHub(), getOpenFilteredHub());
        }
        return modelAppRuntimeErrorOpenFilter;
    }
    
    public HubCopy<AppRuntimeError> createHubCopy() {
        Hub<AppRuntimeError> hubAppRuntimeErrorx = new Hub<>(AppRuntimeError.class);
        HubCopy<AppRuntimeError> hc = new HubCopy<>(getHub(), hubAppRuntimeErrorx, true);
        return hc;
    }
    public AppRuntimeErrorModel createCopy() {
        AppRuntimeErrorModel mod = new AppRuntimeErrorModel(createHubCopy().getHub());
        return mod;
    }
}

