// Generated by OABuilder
package com.viaoa.appstore.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class AppStoreServerModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(AppStoreServerModel.class.getName());
    
    // Hubs
    protected Hub<AppStoreServer> hub;
    // selected appStoreServers
    protected Hub<AppStoreServer> hubMultiSelect;
    // detail hubs
    protected Hub<RunningApp> hubRunningApp;
    
    // ObjectModels
    protected RunningAppModel modelRunningApp;
    
    public AppStoreServerModel() {
        setDisplayName("App Store Server");
        setPluralDisplayName("App Store Servers");
    }
    
    public AppStoreServerModel(Hub<AppStoreServer> hubAppStoreServer) {
        this();
        if (hubAppStoreServer != null) HubDelegate.setObjectClass(hubAppStoreServer, AppStoreServer.class);
        this.hub = hubAppStoreServer;
    }
    public AppStoreServerModel(AppStoreServer appStoreServer) {
        this();
        getHub().add(appStoreServer);
        getHub().setPos(0);
    }
    
    public Hub<AppStoreServer> getOriginalHub() {
        return getHub();
    }
    
    public Hub<RunningApp> getRunningAppHub() {
        if (hubRunningApp != null) return hubRunningApp;
        hubRunningApp = getHub().getDetailHub(AppStoreServer.P_RunningApp);
        return hubRunningApp;
    }
    public AppStoreServer getAppStoreServer() {
        return getHub().getAO();
    }
    
    public Hub<AppStoreServer> getHub() {
        if (hub == null) {
            hub = new Hub<AppStoreServer>(AppStoreServer.class);
        }
        return hub;
    }
    
    public Hub<AppStoreServer> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<AppStoreServer>(AppStoreServer.class);
        }
        return hubMultiSelect;
    }
    
    public RunningAppModel getRunningAppModel() {
        if (modelRunningApp != null) return modelRunningApp;
        modelRunningApp = new RunningAppModel(getRunningAppHub());
        modelRunningApp.setDisplayName("Running App");
        modelRunningApp.setPluralDisplayName("Running Apps");
        modelRunningApp.setForJfc(getForJfc());
        modelRunningApp.setAllowNew(false);
        modelRunningApp.setAllowSave(true);
        modelRunningApp.setAllowAdd(false);
        modelRunningApp.setAllowRemove(false);
        modelRunningApp.setAllowClear(false);
        modelRunningApp.setAllowDelete(false);
        modelRunningApp.setAllowSearch(false);
        modelRunningApp.setAllowHubSearch(false);
        modelRunningApp.setAllowGotoEdit(true);
        modelRunningApp.setViewOnly(true);
        // call AppStoreServer.runningAppModelCallback(RunningAppModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(AppStoreServer.class, AppStoreServer.P_RunningApp, modelRunningApp);
    
        return modelRunningApp;
    }
    
    public HubCopy<AppStoreServer> createHubCopy() {
        Hub<AppStoreServer> hubAppStoreServerx = new Hub<>(AppStoreServer.class);
        HubCopy<AppStoreServer> hc = new HubCopy<>(getHub(), hubAppStoreServerx, true);
        return hc;
    }
    public AppStoreServerModel createCopy() {
        AppStoreServerModel mod = new AppStoreServerModel(createHubCopy().getHub());
        return mod;
    }
}

