// Generated by OABuilder
package com.viaoa.appstore.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class EnvironmentModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(EnvironmentModel.class.getName());
    
    // Hubs
    protected Hub<Environment> hub;
    // selected environments
    protected Hub<Environment> hubMultiSelect;
    // detail hubs
    protected Hub<ServerApplication> hubMergeServerApplications;
    protected Hub<Server> hubServers;
    
    // ObjectModels
    protected ServerApplicationModel modelMergeServerApplications;
    protected ServerModel modelServers;
    
    // SearchModels used for references
    protected ServerApplicationSearchModel modelMergeServerApplicationsSearch;
    protected ServerSearchModel modelServersSearch;
    
    public EnvironmentModel() {
        setDisplayName("Environment");
        setPluralDisplayName("Environments");
    }
    
    public EnvironmentModel(Hub<Environment> hubEnvironment) {
        this();
        if (hubEnvironment != null) HubDelegate.setObjectClass(hubEnvironment, Environment.class);
        this.hub = hubEnvironment;
    }
    public EnvironmentModel(Environment environment) {
        this();
        getHub().add(environment);
        getHub().setPos(0);
    }
    
    public Hub<Environment> getOriginalHub() {
        return getHub();
    }
    
    public Hub<ServerApplication> getMergeServerApplications() {
        if (hubMergeServerApplications == null) {
            hubMergeServerApplications = getHub().getDetailHub(Environment.P_MergeServerApplications);
        }
        return hubMergeServerApplications;
    }
    public Hub<Server> getServers() {
        if (hubServers == null) {
            hubServers = getHub().getDetailHub(Environment.P_Servers);
        }
        return hubServers;
    }
    public Environment getEnvironment() {
        return getHub().getAO();
    }
    
    public Hub<Environment> getHub() {
        if (hub == null) {
            hub = new Hub<Environment>(Environment.class);
        }
        return hub;
    }
    
    public Hub<Environment> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<Environment>(Environment.class);
        }
        return hubMultiSelect;
    }
    
    public ServerApplicationModel getMergeServerApplicationsModel() {
        if (modelMergeServerApplications != null) return modelMergeServerApplications;
        modelMergeServerApplications = new ServerApplicationModel(getMergeServerApplications());
        modelMergeServerApplications.setDisplayName("Server Application");
        modelMergeServerApplications.setPluralDisplayName("Server Applications");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getMergeServerApplications())) {
            modelMergeServerApplications.setCreateUI(false);
        }
        modelMergeServerApplications.setForJfc(getForJfc());
        modelMergeServerApplications.setAllowNew(false);
        modelMergeServerApplications.setAllowSave(false);
        modelMergeServerApplications.setAllowAdd(false);
        modelMergeServerApplications.setAllowMove(false);
        modelMergeServerApplications.setAllowRemove(false);
        modelMergeServerApplications.setAllowDelete(false);
        modelMergeServerApplications.setAllowRefresh(false);
        modelMergeServerApplications.setAllowSearch(false);
        modelMergeServerApplications.setAllowHubSearch(true);
        modelMergeServerApplications.setAllowDownload(true);
        modelMergeServerApplications.setAllowGotoEdit(true);
        modelMergeServerApplications.setViewOnly(getViewOnly());
        modelMergeServerApplications.setAllowTableFilter(true);
        modelMergeServerApplications.setAllowTableSorting(true);
        modelMergeServerApplications.setAllowMultiSelect(false);
        modelMergeServerApplications.setAllowCopy(false);
        modelMergeServerApplications.setAllowCut(false);
        modelMergeServerApplications.setAllowPaste(false);
        // call Environment.mergeServerApplicationsModelCallback(ServerApplicationModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(Environment.class, Environment.P_MergeServerApplications, modelMergeServerApplications);
    
        return modelMergeServerApplications;
    }
    public ServerModel getServersModel() {
        if (modelServers != null) return modelServers;
        modelServers = new ServerModel(getServers());
        modelServers.setDisplayName("Server");
        modelServers.setPluralDisplayName("Servers");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getServers())) {
            modelServers.setCreateUI(false);
        }
        modelServers.setForJfc(getForJfc());
        modelServers.setAllowNew(true);
        modelServers.setAllowSave(true);
        modelServers.setAllowAdd(false);
        modelServers.setAllowMove(false);
        modelServers.setAllowRemove(false);
        modelServers.setAllowDelete(true);
        modelServers.setAllowRefresh(false);
        modelServers.setAllowSearch(false);
        modelServers.setAllowHubSearch(true);
        modelServers.setAllowDownload(true);
        modelServers.setAllowGotoEdit(true);
        modelServers.setViewOnly(getViewOnly());
        modelServers.setAllowTableFilter(true);
        modelServers.setAllowTableSorting(true);
        modelServers.setAllowMultiSelect(false);
        modelServers.setAllowCopy(false);
        modelServers.setAllowCut(false);
        modelServers.setAllowPaste(false);
        // call Environment.serversModelCallback(ServerModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(Environment.class, Environment.P_Servers, modelServers);
    
        return modelServers;
    }
    
    public ServerApplicationSearchModel getMergeServerApplicationsSearchModel() {
        if (modelMergeServerApplicationsSearch != null) return modelMergeServerApplicationsSearch;
        modelMergeServerApplicationsSearch = new ServerApplicationSearchModel();
        return modelMergeServerApplicationsSearch;
    }
    public ServerSearchModel getServersSearchModel() {
        if (modelServersSearch != null) return modelServersSearch;
        modelServersSearch = new ServerSearchModel();
        return modelServersSearch;
    }
    
    public HubCopy<Environment> createHubCopy() {
        Hub<Environment> hubEnvironmentx = new Hub<>(Environment.class);
        HubCopy<Environment> hc = new HubCopy<>(getHub(), hubEnvironmentx, true);
        return hc;
    }
    public EnvironmentModel createCopy() {
        EnvironmentModel mod = new EnvironmentModel(createHubCopy().getHub());
        return mod;
    }
}

