// Generated by OABuilder
package com.viaoa.appstore.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class PropertyValueModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(PropertyValueModel.class.getName());
    
    // Hubs
    protected Hub<PropertyValue> hub;
    // selected propertyValues
    protected Hub<PropertyValue> hubMultiSelect;
    
    
    public PropertyValueModel() {
        setDisplayName("Property Value");
        setPluralDisplayName("Property Values");
    }
    
    public PropertyValueModel(Hub<PropertyValue> hubPropertyValue) {
        this();
        if (hubPropertyValue != null) HubDelegate.setObjectClass(hubPropertyValue, PropertyValue.class);
        this.hub = hubPropertyValue;
    }
    public PropertyValueModel(PropertyValue propertyValue) {
        this();
        getHub().add(propertyValue);
        getHub().setPos(0);
    }
    
    public Hub<PropertyValue> getOriginalHub() {
        return getHub();
    }
    
    public PropertyValue getPropertyValue() {
        return getHub().getAO();
    }
    
    public Hub<PropertyValue> getHub() {
        if (hub == null) {
            hub = new Hub<PropertyValue>(PropertyValue.class);
        }
        return hub;
    }
    
    public Hub<PropertyValue> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<PropertyValue>(PropertyValue.class);
        }
        return hubMultiSelect;
    }
    
    public HubCopy<PropertyValue> createHubCopy() {
        Hub<PropertyValue> hubPropertyValuex = new Hub<>(PropertyValue.class);
        HubCopy<PropertyValue> hc = new HubCopy<>(getHub(), hubPropertyValuex, true);
        return hc;
    }
    public PropertyValueModel createCopy() {
        PropertyValueModel mod = new PropertyValueModel(createHubCopy().getHub());
        return mod;
    }
}

