// Generated by OABuilder
package com.viaoa.appstore.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;
import com.viaoa.model.oa.VInteger;

import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.model.oa.search.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.resource.Resource;

public class ServerApplicationModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(ServerApplicationModel.class.getName());
    
    /* overview
      originalHub   - save the original hub
      groupByApplicationTypeHub - detail hub of selected ServerApplication
      groupByEnvironmentHub - detail hub of selected ServerApplication
      <- hub - points to groupBy or original hub
    */
    
    // types of ways to view the original hub
    public static final int TYPE_Original = 0;
    public static final int TYPE_GroupByApplicationType = 1;
    public static final int TYPE_GroupByEnvironment = 2;
    
    // Hubs
    protected Hub<ServerApplication> hubOriginal;
    // groupBy ApplicationType
    protected Hub<ApplicationType> hubGroupedByApplicationType;
    protected Hub<ServerApplication> hubServerApplicationsGroupedByApplicationType;
    protected HubGroupBy<ServerApplication, ApplicationType> hgbApplicationType;
    
    // groupBy Environment
    protected Hub<Environment> hubGroupedByEnvironment;
    protected Hub<ServerApplication> hubServerApplicationsGroupedByEnvironment;
    protected HubGroupBy<ServerApplication, Environment> hgbEnvironment;
    
    // main hub that points to hubOriginal, groupedBy hub
    protected Hub<ServerApplication> hub;
    // selected serverApplications
    protected Hub<ServerApplication> hubMultiSelect;
    // detail hubs
    protected Hub<ApplicationType> hubApplicationType;
    protected Hub<ApplicationVersion> hubApplicationVersion;
    protected Hub<RunningApp> hubRunningApp;
    protected Hub<Server> hubServer;
    protected Hub<ClientApp> hubClientApps;
    protected Hub<PropertyValue> hubPropertyValues;
    
    // AddHubs used for references
    protected Hub<ApplicationType> hubApplicationTypeSelectFrom;
    protected Hub<ApplicationVersion> hubApplicationVersionSelectFrom;
    
    // ObjectModels
    protected ApplicationTypeModel modelApplicationType;
    protected ApplicationVersionModel modelApplicationVersion;
    protected RunningAppModel modelRunningApp;
    protected ServerModel modelServer;
    protected ClientAppModel modelClientApps;
    protected PropertyValueModel modelPropertyValues;
    protected ApplicationTypeModel modelGroupedByApplicationType;
    protected ServerApplicationModel modelServerApplicationsGroupedByApplicationType;
    protected EnvironmentModel modelGroupedByEnvironment;
    protected ServerApplicationModel modelServerApplicationsGroupedByEnvironment;
    
    // selectFrom
    protected ApplicationTypeModel modelApplicationTypeSelectFrom;
    protected ApplicationVersionModel modelApplicationVersionSelectFrom;
    
    // SearchModels used for references
    protected ApplicationTypeSearchModel modelApplicationTypeSearch;
    protected ApplicationVersionSearchModel modelApplicationVersionSearch;
    protected RunningAppSearchModel modelRunningAppSearch;
    protected ServerSearchModel modelServerSearch;
    protected PropertyValueSearchModel modelPropertyValuesSearch;
    
    public ServerApplicationModel() {
        setDisplayName("Server Application");
        setPluralDisplayName("Server Applications");
    }
    
    public ServerApplicationModel(Hub<ServerApplication> hubServerApplication) {
        this();
        if (hubServerApplication != null) HubDelegate.setObjectClass(hubServerApplication, ServerApplication.class);
        this.hubOriginal = hubServerApplication;
        setType(TYPE_Original);
    }
    public ServerApplicationModel(ServerApplication serverApplication) {
        this();
        getOriginalHub().add(serverApplication);
        getOriginalHub().setPos(0);
        setType(TYPE_Original);
    }
    
    // the type of hub that is active
    public void setType(int type) {
        updateType(type);
        getVType().setValue(type);
    }
    public int getType() {
        return getVType().getValue();
    }
    // listen to type change
    public void addTypeListener(HubListener hl) {
        if (hl != null) getTypeHub().addHubListener(hl);
    }
    // used to listen to type change
    private Hub<VInteger> hubType;
    private VInteger type;
    private VInteger getVType() {
        if (type == null) {
            type = new VInteger();
        }
        return type;
    }
    private Hub<VInteger> getTypeHub() {
        if (hubType == null) {
            hubType = new Hub<VInteger>(VInteger.class);
            hubType.add(getVType());
            hubType.setPos(0);
        }
        return hubType;
    }
    private void updateType(int newValue) {
        if (!getAllowRecursive()) newValue = TYPE_Original;
        switch (newValue) {
        case TYPE_Original:
            getHub().setSharedHub(getOriginalHub(), true);
            break;
        case TYPE_GroupByApplicationType:
            getHub().setSharedHub(getServerApplicationsGroupedByApplicationTypeHub(), true);
            break;
        case TYPE_GroupByEnvironment:
            getHub().setSharedHub(getServerApplicationsGroupedByEnvironmentHub(), true);
            break;
        }
    }
    
    public Hub<ServerApplication> getOriginalHub() {
        if (hubOriginal == null) {
            hubOriginal = new Hub<ServerApplication>(ServerApplication.class);
        }
        return hubOriginal;
    }
    
    public Hub<ApplicationType> getApplicationTypeHub() {
        if (hubApplicationType != null) return hubApplicationType;
        hubApplicationType = getHub().getDetailHub(ServerApplication.P_ApplicationType);
        return hubApplicationType;
    }
    public Hub<ApplicationVersion> getApplicationVersionHub() {
        if (hubApplicationVersion != null) return hubApplicationVersion;
        hubApplicationVersion = getHub().getDetailHub(ServerApplication.P_ApplicationVersion);
        return hubApplicationVersion;
    }
    public Hub<RunningApp> getRunningAppHub() {
        if (hubRunningApp != null) return hubRunningApp;
        hubRunningApp = getHub().getDetailHub(ServerApplication.P_RunningApp);
        return hubRunningApp;
    }
    public Hub<Server> getServerHub() {
        if (hubServer != null) return hubServer;
        // this is the owner, use detailHub
        hubServer = getHub().getDetailHub(ServerApplication.P_Server);
        return hubServer;
    }
    public Hub<ClientApp> getClientApps() {
        if (hubClientApps == null) {
            hubClientApps = getHub().getDetailHub(ServerApplication.P_ClientApps);
        }
        return hubClientApps;
    }
    public Hub<PropertyValue> getPropertyValues() {
        if (hubPropertyValues == null) {
            hubPropertyValues = getHub().getDetailHub(ServerApplication.P_PropertyValues);
        }
        return hubPropertyValues;
    }
    public Hub<ApplicationType> getApplicationTypeSelectFromHub() {
        if (hubApplicationTypeSelectFrom != null) return hubApplicationTypeSelectFrom;
        hubApplicationTypeSelectFrom = new Hub<ApplicationType>(ApplicationType.class);
        Hub<ApplicationType> hubApplicationTypeSelectFrom1 = ModelDelegate.getApplicationTypes().createSharedHub();
        HubCombined<ApplicationType> hubCombined = new HubCombined(hubApplicationTypeSelectFrom, hubApplicationTypeSelectFrom1, getApplicationTypeHub());
        hubApplicationTypeSelectFrom.setLinkHub(getHub(), ServerApplication.P_ApplicationType); 
        return hubApplicationTypeSelectFrom;
    }
    public Hub<ApplicationVersion> getApplicationVersionSelectFromHub() {
        if (hubApplicationVersionSelectFrom != null) return hubApplicationVersionSelectFrom;
        hubApplicationVersionSelectFrom = new Hub<ApplicationVersion>(ApplicationVersion.class);
        Hub<ApplicationVersion>hubApplicationVersionSelectFrom1 = new Hub<ApplicationVersion>(ApplicationVersion.class);
        new HubMerger(getHub(), hubApplicationVersionSelectFrom1, ServerApplicationPP.applicationType().applicationVersions().pp, false);
        HubCombined<ApplicationVersion> hubCombined = new HubCombined(hubApplicationVersionSelectFrom, hubApplicationVersionSelectFrom1, getApplicationVersionHub());
        hubApplicationVersionSelectFrom.setLinkHub(getHub(), ServerApplication.P_ApplicationVersion); 
        return hubApplicationVersionSelectFrom;
    }
    public Hub<ApplicationType> getGroupedByApplicationTypeHub() {
        if (hubGroupedByApplicationType == null) {
            hubGroupedByApplicationType = getGroupedByApplicationType().getMasterHub();
        }
        return hubGroupedByApplicationType;
    }
    public Hub<ServerApplication> getServerApplicationsGroupedByApplicationTypeHub() {
        if (hubServerApplicationsGroupedByApplicationType == null) {
            hubServerApplicationsGroupedByApplicationType = getGroupedByApplicationType().getDetailHub();
        }
        return hubServerApplicationsGroupedByApplicationType;
    }
    protected HubGroupBy<ServerApplication, ApplicationType> getGroupedByApplicationType() {
        if (hgbApplicationType == null) {
            String pp = ServerApplicationPP.applicationType().pp;
            hgbApplicationType = new HubGroupBy<ServerApplication, ApplicationType>(getOriginalHub(), pp);
        }
        return hgbApplicationType;
    }
    
    public Hub<Environment> getGroupedByEnvironmentHub() {
        if (hubGroupedByEnvironment == null) {
            hubGroupedByEnvironment = getGroupedByEnvironment().getMasterHub();
        }
        return hubGroupedByEnvironment;
    }
    public Hub<ServerApplication> getServerApplicationsGroupedByEnvironmentHub() {
        if (hubServerApplicationsGroupedByEnvironment == null) {
            hubServerApplicationsGroupedByEnvironment = getGroupedByEnvironment().getDetailHub();
        }
        return hubServerApplicationsGroupedByEnvironment;
    }
    protected HubGroupBy<ServerApplication, Environment> getGroupedByEnvironment() {
        if (hgbEnvironment == null) {
            String pp = ServerApplicationPP.server().environment().pp;
            hgbEnvironment = new HubGroupBy<ServerApplication, Environment>(getOriginalHub(), pp);
        }
        return hgbEnvironment;
    }
    
    public ServerApplication getServerApplication() {
        return getHub().getAO();
    }
    
    public Hub<ServerApplication> getHub() {
        if (hub == null) {
            hub = new Hub<ServerApplication>(ServerApplication.class);
            hub.setSharedHub(getOriginalHub(), true);
        }
        return hub;
    }
    
    public Hub<ServerApplication> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<ServerApplication>(ServerApplication.class);
        }
        return hubMultiSelect;
    }
    
    public ApplicationTypeModel getApplicationTypeModel() {
        if (modelApplicationType != null) return modelApplicationType;
        modelApplicationType = new ApplicationTypeModel(getApplicationTypeHub());
        modelApplicationType.setDisplayName("Application Type");
        modelApplicationType.setPluralDisplayName("Application Types");
        modelApplicationType.setForJfc(getForJfc());
        modelApplicationType.setAllowNew(false);
        modelApplicationType.setAllowSave(true);
        modelApplicationType.setAllowAdd(false);
        modelApplicationType.setAllowRemove(false);
        modelApplicationType.setAllowClear(false);
        modelApplicationType.setAllowDelete(false);
        modelApplicationType.setAllowSearch(false);
        modelApplicationType.setAllowHubSearch(true);
        modelApplicationType.setAllowGotoEdit(true);
        modelApplicationType.setViewOnly(getViewOnly());
        // call ServerApplication.applicationTypeModelCallback(ApplicationTypeModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ServerApplication.class, ServerApplication.P_ApplicationType, modelApplicationType);
    
        return modelApplicationType;
    }
    public ApplicationVersionModel getApplicationVersionModel() {
        if (modelApplicationVersion != null) return modelApplicationVersion;
        modelApplicationVersion = new ApplicationVersionModel(getApplicationVersionHub());
        modelApplicationVersion.setDisplayName("Application Version");
        modelApplicationVersion.setPluralDisplayName("Application Versions");
        modelApplicationVersion.setForJfc(getForJfc());
        modelApplicationVersion.setAllowNew(false);
        modelApplicationVersion.setAllowSave(true);
        modelApplicationVersion.setAllowAdd(false);
        modelApplicationVersion.setAllowRemove(true);
        modelApplicationVersion.setAllowClear(true);
        modelApplicationVersion.setAllowDelete(false);
        modelApplicationVersion.setAllowSearch(true);
        modelApplicationVersion.setAllowHubSearch(true);
        modelApplicationVersion.setAllowGotoEdit(true);
        modelApplicationVersion.setViewOnly(true);
        // call ServerApplication.applicationVersionModelCallback(ApplicationVersionModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ServerApplication.class, ServerApplication.P_ApplicationVersion, modelApplicationVersion);
    
        return modelApplicationVersion;
    }
    public RunningAppModel getRunningAppModel() {
        if (modelRunningApp != null) return modelRunningApp;
        modelRunningApp = new RunningAppModel(getRunningAppHub());
        modelRunningApp.setDisplayName("Running App");
        modelRunningApp.setPluralDisplayName("Running Apps");
        modelRunningApp.setForJfc(getForJfc());
        modelRunningApp.setAllowNew(true);
        modelRunningApp.setAllowSave(true);
        modelRunningApp.setAllowAdd(false);
        modelRunningApp.setAllowRemove(true);
        modelRunningApp.setAllowClear(true);
        modelRunningApp.setAllowDelete(false);
        modelRunningApp.setAllowSearch(true);
        modelRunningApp.setAllowHubSearch(false);
        modelRunningApp.setAllowGotoEdit(true);
        modelRunningApp.setViewOnly(getViewOnly());
        // call ServerApplication.runningAppModelCallback(RunningAppModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ServerApplication.class, ServerApplication.P_RunningApp, modelRunningApp);
    
        return modelRunningApp;
    }
    public ServerModel getServerModel() {
        if (modelServer != null) return modelServer;
        modelServer = new ServerModel(getServerHub());
        modelServer.setDisplayName("Server");
        modelServer.setPluralDisplayName("Servers");
        modelServer.setForJfc(getForJfc());
        modelServer.setAllowNew(false);
        modelServer.setAllowSave(true);
        modelServer.setAllowAdd(false);
        modelServer.setAllowRemove(false);
        modelServer.setAllowClear(false);
        modelServer.setAllowDelete(false);
        modelServer.setAllowSearch(false);
        modelServer.setAllowHubSearch(true);
        modelServer.setAllowGotoEdit(true);
        OALinkInfo li = HubDetailDelegate.getLinkInfoFromDetailToMaster(getOriginalHub());
        modelServer.setCreateUI(li == null || !ServerApplication.P_Server.equalsIgnoreCase(li.getName()) );
        modelServer.setViewOnly(getViewOnly());
        // call ServerApplication.serverModelCallback(ServerModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ServerApplication.class, ServerApplication.P_Server, modelServer);
    
        return modelServer;
    }
    public ClientAppModel getClientAppsModel() {
        if (modelClientApps != null) return modelClientApps;
        modelClientApps = new ClientAppModel(getClientApps());
        modelClientApps.setDisplayName("Client App");
        modelClientApps.setPluralDisplayName("Client Apps");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getClientApps())) {
            modelClientApps.setCreateUI(false);
        }
        modelClientApps.setForJfc(getForJfc());
        modelClientApps.setAllowNew(false);
        modelClientApps.setAllowSave(true);
        modelClientApps.setAllowAdd(false);
        modelClientApps.setAllowMove(false);
        modelClientApps.setAllowRemove(false);
        modelClientApps.setAllowDelete(true);
        modelClientApps.setAllowRefresh(false);
        modelClientApps.setAllowSearch(false);
        modelClientApps.setAllowHubSearch(false);
        modelClientApps.setAllowDownload(true);
        modelClientApps.setAllowGotoEdit(true);
        modelClientApps.setViewOnly(getViewOnly());
        modelClientApps.setAllowTableFilter(true);
        modelClientApps.setAllowTableSorting(true);
        modelClientApps.setAllowMultiSelect(false);
        modelClientApps.setAllowCopy(false);
        modelClientApps.setAllowCut(false);
        modelClientApps.setAllowPaste(false);
        // call ServerApplication.clientAppsModelCallback(ClientAppModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ServerApplication.class, ServerApplication.P_ClientApps, modelClientApps);
    
        return modelClientApps;
    }
    public PropertyValueModel getPropertyValuesModel() {
        if (modelPropertyValues != null) return modelPropertyValues;
        modelPropertyValues = new PropertyValueModel(getPropertyValues());
        modelPropertyValues.setDisplayName("Property Value");
        modelPropertyValues.setPluralDisplayName("Property Values");
        if (HubDetailDelegate.getIsFromSameMasterHub(getOriginalHub(), getPropertyValues())) {
            modelPropertyValues.setCreateUI(false);
        }
        modelPropertyValues.setForJfc(getForJfc());
        modelPropertyValues.setAllowNew(true);
        modelPropertyValues.setAllowSave(true);
        modelPropertyValues.setAllowAdd(true);
        modelPropertyValues.setAllowMove(false);
        modelPropertyValues.setAllowRemove(true);
        modelPropertyValues.setAllowDelete(false);
        modelPropertyValues.setAllowRefresh(false);
        modelPropertyValues.setAllowSearch(false);
        modelPropertyValues.setAllowHubSearch(false);
        modelPropertyValues.setAllowDownload(true);
        modelPropertyValues.setAllowGotoEdit(true);
        modelPropertyValues.setViewOnly(getViewOnly());
        modelPropertyValues.setAllowTableFilter(true);
        modelPropertyValues.setAllowTableSorting(true);
        modelPropertyValues.setAllowMultiSelect(false);
        modelPropertyValues.setAllowCopy(false);
        modelPropertyValues.setAllowCut(false);
        modelPropertyValues.setAllowPaste(false);
        // call ServerApplication.propertyValuesModelCallback(PropertyValueModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(ServerApplication.class, ServerApplication.P_PropertyValues, modelPropertyValues);
    
        return modelPropertyValues;
    }
    
    public ApplicationTypeModel getGroupedByApplicationTypeModel() {
        if (modelGroupedByApplicationType != null) return modelGroupedByApplicationType;
        modelGroupedByApplicationType = new ApplicationTypeModel(getGroupedByApplicationTypeHub());
        modelGroupedByApplicationType.setDisplayName("Application Type");
        modelGroupedByApplicationType.setPluralDisplayName("Application Type");
        modelGroupedByApplicationType.setAllowNew(false);
        modelGroupedByApplicationType.setAllowSave(false);
        modelGroupedByApplicationType.setAllowAdd(false);
        modelGroupedByApplicationType.setAllowRemove(false);
        modelGroupedByApplicationType.setAllowDelete(false);
        modelGroupedByApplicationType.setAllowSearch(false);
        modelGroupedByApplicationType.setAllowHubSearch(true);
        modelGroupedByApplicationType.setAllowGotoEdit(true);
        modelGroupedByApplicationType.setForJfc(getForJfc());
        return modelGroupedByApplicationType;
    }
    public ServerApplicationModel getServerApplicationsGroupedByApplicationTypeModel() {
        if (modelServerApplicationsGroupedByApplicationType != null) return modelServerApplicationsGroupedByApplicationType;
        modelServerApplicationsGroupedByApplicationType = new ServerApplicationModel(getServerApplicationsGroupedByApplicationTypeHub());
        modelServerApplicationsGroupedByApplicationType.setDisplayName("Server Application");
        modelServerApplicationsGroupedByApplicationType.setPluralDisplayName("Server Applications");
        modelServerApplicationsGroupedByApplicationType.setAllowSave(false);
        modelServerApplicationsGroupedByApplicationType.setAllowNew(false);
        modelServerApplicationsGroupedByApplicationType.setAllowAdd(false);
        modelServerApplicationsGroupedByApplicationType.setAllowRemove(false);
        modelServerApplicationsGroupedByApplicationType.setAllowDelete(false);
        modelServerApplicationsGroupedByApplicationType.setAllowSearch(false);
        modelServerApplicationsGroupedByApplicationType.setAllowHubSearch(true);
        modelServerApplicationsGroupedByApplicationType.setAllowGotoEdit(true);
        modelServerApplicationsGroupedByApplicationType.setForJfc(getForJfc());
        return modelServerApplicationsGroupedByApplicationType;
    }
    
    public EnvironmentModel getGroupedByEnvironmentModel() {
        if (modelGroupedByEnvironment != null) return modelGroupedByEnvironment;
        modelGroupedByEnvironment = new EnvironmentModel(getGroupedByEnvironmentHub());
        modelGroupedByEnvironment.setDisplayName("Environment");
        modelGroupedByEnvironment.setPluralDisplayName("Environment");
        modelGroupedByEnvironment.setAllowNew(false);
        modelGroupedByEnvironment.setAllowSave(false);
        modelGroupedByEnvironment.setAllowAdd(false);
        modelGroupedByEnvironment.setAllowRemove(false);
        modelGroupedByEnvironment.setAllowDelete(false);
        modelGroupedByEnvironment.setAllowSearch(false);
        modelGroupedByEnvironment.setAllowHubSearch(true);
        modelGroupedByEnvironment.setAllowGotoEdit(true);
        modelGroupedByEnvironment.setForJfc(getForJfc());
        return modelGroupedByEnvironment;
    }
    public ServerApplicationModel getServerApplicationsGroupedByEnvironmentModel() {
        if (modelServerApplicationsGroupedByEnvironment != null) return modelServerApplicationsGroupedByEnvironment;
        modelServerApplicationsGroupedByEnvironment = new ServerApplicationModel(getServerApplicationsGroupedByEnvironmentHub());
        modelServerApplicationsGroupedByEnvironment.setDisplayName("Server Application");
        modelServerApplicationsGroupedByEnvironment.setPluralDisplayName("Server Applications");
        modelServerApplicationsGroupedByEnvironment.setAllowSave(false);
        modelServerApplicationsGroupedByEnvironment.setAllowNew(false);
        modelServerApplicationsGroupedByEnvironment.setAllowAdd(false);
        modelServerApplicationsGroupedByEnvironment.setAllowRemove(false);
        modelServerApplicationsGroupedByEnvironment.setAllowDelete(false);
        modelServerApplicationsGroupedByEnvironment.setAllowSearch(false);
        modelServerApplicationsGroupedByEnvironment.setAllowHubSearch(true);
        modelServerApplicationsGroupedByEnvironment.setAllowGotoEdit(true);
        modelServerApplicationsGroupedByEnvironment.setForJfc(getForJfc());
        return modelServerApplicationsGroupedByEnvironment;
    }
    
    
    public ApplicationTypeModel getApplicationTypeSelectFromModel() {
        if (modelApplicationTypeSelectFrom != null) return modelApplicationTypeSelectFrom;
        modelApplicationTypeSelectFrom = new ApplicationTypeModel(getApplicationTypeSelectFromHub());
        modelApplicationTypeSelectFrom.setDisplayName("Application Type");
        modelApplicationTypeSelectFrom.setPluralDisplayName("Application Types");
        modelApplicationTypeSelectFrom.setForJfc(getForJfc());
        modelApplicationTypeSelectFrom.setAllowNew(false);
        modelApplicationTypeSelectFrom.setAllowSave(true);
        modelApplicationTypeSelectFrom.setAllowAdd(false);
        modelApplicationTypeSelectFrom.setAllowMove(false);
        modelApplicationTypeSelectFrom.setAllowRemove(false);
        modelApplicationTypeSelectFrom.setAllowDelete(false);
        modelApplicationTypeSelectFrom.setAllowSearch(false);
        modelApplicationTypeSelectFrom.setAllowHubSearch(true);
        modelApplicationTypeSelectFrom.setAllowGotoEdit(true);
        modelApplicationTypeSelectFrom.setViewOnly(getViewOnly());
        modelApplicationTypeSelectFrom.setAllowNew(false);
        modelApplicationTypeSelectFrom.setAllowTableFilter(true);
        modelApplicationTypeSelectFrom.setAllowTableSorting(true);
        modelApplicationTypeSelectFrom.setAllowCut(false);
        modelApplicationTypeSelectFrom.setAllowCopy(false);
        modelApplicationTypeSelectFrom.setAllowPaste(false);
        modelApplicationTypeSelectFrom.setAllowMultiSelect(false);
        return modelApplicationTypeSelectFrom;
    }
    public ApplicationVersionModel getApplicationVersionSelectFromModel() {
        if (modelApplicationVersionSelectFrom != null) return modelApplicationVersionSelectFrom;
        modelApplicationVersionSelectFrom = new ApplicationVersionModel(getApplicationVersionSelectFromHub());
        modelApplicationVersionSelectFrom.setDisplayName("Application Version");
        modelApplicationVersionSelectFrom.setPluralDisplayName("Application Versions");
        modelApplicationVersionSelectFrom.setForJfc(getForJfc());
        modelApplicationVersionSelectFrom.setAllowNew(false);
        modelApplicationVersionSelectFrom.setAllowSave(true);
        modelApplicationVersionSelectFrom.setAllowAdd(false);
        modelApplicationVersionSelectFrom.setAllowMove(false);
        modelApplicationVersionSelectFrom.setAllowRemove(false);
        modelApplicationVersionSelectFrom.setAllowDelete(false);
        modelApplicationVersionSelectFrom.setAllowSearch(true);
        modelApplicationVersionSelectFrom.setAllowHubSearch(true);
        modelApplicationVersionSelectFrom.setAllowGotoEdit(true);
        modelApplicationVersionSelectFrom.setViewOnly(getViewOnly());
        modelApplicationVersionSelectFrom.setAllowNew(false);
        modelApplicationVersionSelectFrom.setAllowTableFilter(true);
        modelApplicationVersionSelectFrom.setAllowTableSorting(true);
        modelApplicationVersionSelectFrom.setAllowCut(false);
        modelApplicationVersionSelectFrom.setAllowCopy(false);
        modelApplicationVersionSelectFrom.setAllowPaste(false);
        modelApplicationVersionSelectFrom.setAllowMultiSelect(false);
        return modelApplicationVersionSelectFrom;
    }
    public ApplicationTypeSearchModel getApplicationTypeSearchModel() {
        if (modelApplicationTypeSearch != null) return modelApplicationTypeSearch;
        modelApplicationTypeSearch = new ApplicationTypeSearchModel();
        HubSelectDelegate.adoptWhereHub(modelApplicationTypeSearch.getHub(), ServerApplication.P_ApplicationType, getHub());
        return modelApplicationTypeSearch;
    }
    public ApplicationVersionSearchModel getApplicationVersionSearchModel() {
        if (modelApplicationVersionSearch != null) return modelApplicationVersionSearch;
        modelApplicationVersionSearch = new ApplicationVersionSearchModel();
        OAFilter filter = new OAInFilter(ServerApplicationModel.this.getHub(), ServerApplicationPP.applicationType().applicationVersions().pp);
        modelApplicationVersionSearch.getApplicationVersionSearch().setExtraWhereFilter(filter);
        return modelApplicationVersionSearch;
    }
    public RunningAppSearchModel getRunningAppSearchModel() {
        if (modelRunningAppSearch != null) return modelRunningAppSearch;
        modelRunningAppSearch = new RunningAppSearchModel();
        HubSelectDelegate.adoptWhereHub(modelRunningAppSearch.getHub(), ServerApplication.P_RunningApp, getHub());
        return modelRunningAppSearch;
    }
    public ServerSearchModel getServerSearchModel() {
        if (modelServerSearch != null) return modelServerSearch;
        modelServerSearch = new ServerSearchModel();
        HubSelectDelegate.adoptWhereHub(modelServerSearch.getHub(), ServerApplication.P_Server, getHub());
        return modelServerSearch;
    }
    public PropertyValueSearchModel getPropertyValuesSearchModel() {
        if (modelPropertyValuesSearch != null) return modelPropertyValuesSearch;
        modelPropertyValuesSearch = new PropertyValueSearchModel();
        return modelPropertyValuesSearch;
    }
    
    public HubCopy<ServerApplication> createHubCopy() {
        Hub<ServerApplication> hubServerApplicationx = new Hub<>(ServerApplication.class);
        HubCopy<ServerApplication> hc = new HubCopy<>(getHub(), hubServerApplicationx, true);
        return hc;
    }
    public ServerApplicationModel createCopy() {
        ServerApplicationModel mod = new ServerApplicationModel(createHubCopy().getHub());
        return mod;
    }
}

