// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.myApps;

import java.util.logging.Logger;

public class MyAppsPanel extends MyAppsPanelBase {
    private static Logger LOG = Logger.getLogger(MyAppsPanel.class.getName());
}
