// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.myApps;

import java.util.logging.*;

public class MyClientApssBar extends MyClientApssBarBase {
    private static Logger LOG = Logger.getLogger(MyClientApssBarBase.class.getName());
}
