// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.myApps;

import java.util.logging.*;

public class MyServerAppsBar extends MyServerAppsBarBase {
    private static Logger LOG = Logger.getLogger(MyServerAppsBarBase.class.getName());
}
