// Generated by OABuilder 
package com.viaoa.appstore.view.client.panel.myApps;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.*;
import javax.swing.*;
import com.viaoa.appstore.delegate.ModelDelegate;
import com.viaoa.appstore.model.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.search.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.appstore.resource.Resource;
import com.viaoa.appstore.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;

public class MySingleUserAppsBarBase {
    private static Logger LOG = Logger.getLogger(MySingleUserAppsBarBase.class.getName());
    
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    protected OATree tree;
    
    public static final String CARD_Splash = "splash";
    public static final String CARD_AppUserSingleApps = "AppUserSingleApps";
    
    public MySingleUserAppsBarBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        setup();
    }
    
    public JPanel getPanel() {
        return cardPanel;
    }
    
    protected void setup() {
        ImageIcon icon = Resource.getJarIcon("myAppsSplash.png");
        JLabel lbl = new JLabel("My Single User Apps", icon, JLabel.CENTER);
        lbl.setFont(lbl.getFont().deriveFont(20.0f));
        lbl.setVerticalTextPosition(SwingConstants.TOP);
        lbl.setHorizontalTextPosition(SwingConstants.CENTER);
        cardPanel.add(lbl, CARD_Splash);
        cardLayout.show(cardPanel, CARD_Splash);
    
        getTree();
        OATreeTitleNode ttNode;
    
        // AppUserSingleApps - Single User Apps - 
        AppUserModel modelAppUser = new AppUserModel(ModelDelegate.getLocalAppUserHub());
        AppUserJfc jfcAppUser = new AppUserJfc(modelAppUser) {
            JPanel panx;
            @Override
            public void showCardPanel(final String name) {
                MySingleUserAppsBarBase.this.cardLayout.show(MySingleUserAppsBarBase.this.cardPanel, CARD_AppUserSingleApps);
                if (panx != null) return;
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    volatile Exception ex;
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            panx = getSingleAppsJfc().getCardPanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating SingleAppJfc", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panx == null) panx = new JPanel();
                        MySingleUserAppsBarBase.this.cardPanel.add(panx, CARD_AppUserSingleApps);
                        showCardPanel(name);
                    }
                };
                sw.execute();
            }
        };
        jfcAppUser.createSingleAppsJfc(false);
        SingleAppJfc jfcSingleApps = jfcAppUser.getSingleAppsJfc();
        ttNode = jfcSingleApps.getTreeTitleNode();
        tree.add(ttNode);
        ttNode.add(jfcSingleApps.getTreeNode());
        cardPanel.add(new JLabel("loading Single User Apps ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_AppUserSingleApps);
    }
    protected OATree getTree() {
        if (tree != null) return tree;
        tree = new OATree(18) {
            @Override
            public void nodeSelected(OATreeNode node) {
                super.nodeSelected(node);
                if (node == null) {
                    MySingleUserAppsBarBase.this.cardLayout.show(MySingleUserAppsBarBase.this.cardPanel, MySingleUserAppsBarBase.this.CARD_Splash);
                }
            }
        };
        tree.setAllowDnD(true);
        return tree;
    }
}

