// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import com.viaoa.appstore.model.oa.*;
 
public class AppRuntimeErrorPP {
    private static AppRuntimePPx appRuntime;
     

    public static AppRuntimePPx appRuntime() {
        if (appRuntime == null) appRuntime = new AppRuntimePPx(AppRuntimeError.P_AppRuntime);
        return appRuntime;
    }

    public static String id() {
        String s = AppRuntimeError.P_Id;
        return s;
    }

    public static String created() {
        String s = AppRuntimeError.P_Created;
        return s;
    }

    public static String message() {
        String s = AppRuntimeError.P_Message;
        return s;
    }

    public static String ack() {
        String s = AppRuntimeError.P_Ack;
        return s;
    }

    public static String stackTrace() {
        String s = AppRuntimeError.P_StackTrace;
        return s;
    }

    public static String acknowledge() {
        String s = "acknowledge";
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
