// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.appstore.model.oa.*;
 
public class PropertyValuePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public PropertyValuePPx(String name) {
        this(null, name);
    }

    public PropertyValuePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ApplicationTypePPx applicationType() {
        ApplicationTypePPx ppx = new ApplicationTypePPx(this, PropertyValue.P_ApplicationType);
        return ppx;
    }

    public ClientAppPPx clientApp() {
        ClientAppPPx ppx = new ClientAppPPx(this, PropertyValue.P_ClientApp);
        return ppx;
    }

    public ServerApplicationPPx serverApplication() {
        ServerApplicationPPx ppx = new ServerApplicationPPx(this, PropertyValue.P_ServerApplication);
        return ppx;
    }

    public SingleAppPPx singleApp() {
        SingleAppPPx ppx = new SingleAppPPx(this, PropertyValue.P_SingleApp);
        return ppx;
    }

    public String id() {
        return pp + "." + PropertyValue.P_Id;
    }

    public String created() {
        return pp + "." + PropertyValue.P_Created;
    }

    public String name() {
        return pp + "." + PropertyValue.P_Name;
    }

    public String value() {
        return pp + "." + PropertyValue.P_Value;
    }

    public String ignore() {
        return pp + "." + PropertyValue.P_Ignore;
    }

    public String note() {
        return pp + "." + PropertyValue.P_Note;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
