// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import com.viaoa.appstore.model.oa.*;
 
public class RunningAppPP {
    private static AppStoreServerPPx appStoreServer;
    private static AppUserLoginPPx appUserLogin;
    private static ClientAppPPx clientApp;
    private static ServerApplicationPPx serverApplication;
    private static SingleAppPPx singleApp;
     

    public static AppStoreServerPPx appStoreServer() {
        if (appStoreServer == null) appStoreServer = new AppStoreServerPPx(RunningApp.P_AppStoreServer);
        return appStoreServer;
    }

    public static AppUserLoginPPx appUserLogin() {
        if (appUserLogin == null) appUserLogin = new AppUserLoginPPx(RunningApp.P_AppUserLogin);
        return appUserLogin;
    }

    public static ClientAppPPx clientApp() {
        if (clientApp == null) clientApp = new ClientAppPPx(RunningApp.P_ClientApp);
        return clientApp;
    }

    public static ServerApplicationPPx serverApplication() {
        if (serverApplication == null) serverApplication = new ServerApplicationPPx(RunningApp.P_ServerApplication);
        return serverApplication;
    }

    public static SingleAppPPx singleApp() {
        if (singleApp == null) singleApp = new SingleAppPPx(RunningApp.P_SingleApp);
        return singleApp;
    }

    public static String id() {
        String s = RunningApp.P_Id;
        return s;
    }

    public static String created() {
        String s = RunningApp.P_Created;
        return s;
    }

    public static String stopRequest() {
        String s = RunningApp.P_StopRequest;
        return s;
    }

    public static String pid() {
        String s = RunningApp.P_Pid;
        return s;
    }

    public static String error() {
        String s = RunningApp.P_Error;
        return s;
    }

    public static String cpuSeconds() {
        String s = RunningApp.P_CpuSeconds;
        return s;
    }

    public static String stopped() {
        String s = RunningApp.P_Stopped;
        return s;
    }

    public static String stopProcess() {
        String s = "stopProcess";
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
