// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.appstore.model.oa.*;
 
public class ServerApplicationPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public ServerApplicationPPx(String name) {
        this(null, name);
    }

    public ServerApplicationPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ApplicationTypePPx applicationType() {
        ApplicationTypePPx ppx = new ApplicationTypePPx(this, ServerApplication.P_ApplicationType);
        return ppx;
    }

    public ApplicationVersionPPx applicationVersion() {
        ApplicationVersionPPx ppx = new ApplicationVersionPPx(this, ServerApplication.P_ApplicationVersion);
        return ppx;
    }

    public ClientAppPPx clientApps() {
        ClientAppPPx ppx = new ClientAppPPx(this, ServerApplication.P_ClientApps);
        return ppx;
    }

    public AppUserPPx mergeAppUsers() {
        AppUserPPx ppx = new AppUserPPx(this, ServerApplication.P_MergeAppUsers);
        return ppx;
    }

    public EnvironmentPPx mergeEnvironment() {
        EnvironmentPPx ppx = new EnvironmentPPx(this, ServerApplication.P_MergeEnvironment);
        return ppx;
    }

    public PropertyValuePPx propertyValues() {
        PropertyValuePPx ppx = new PropertyValuePPx(this, ServerApplication.P_PropertyValues);
        return ppx;
    }

    public RunningAppPPx runningApp() {
        RunningAppPPx ppx = new RunningAppPPx(this, ServerApplication.P_RunningApp);
        return ppx;
    }

    public ServerPPx server() {
        ServerPPx ppx = new ServerPPx(this, ServerApplication.P_Server);
        return ppx;
    }

    public String id() {
        return pp + "." + ServerApplication.P_Id;
    }

    public String created() {
        return pp + "." + ServerApplication.P_Created;
    }

    public String name() {
        return pp + "." + ServerApplication.P_Name;
    }

    public String clientPort() {
        return pp + "." + ServerApplication.P_ClientPort;
    }

    public String httpPort() {
        return pp + "." + ServerApplication.P_HttpPort;
    }

    public String httpsPort() {
        return pp + "." + ServerApplication.P_HttpsPort;
    }

    public String lastConnect() {
        return pp + "." + ServerApplication.P_LastConnect;
    }

    public String calcFullName() {
        return pp + "." + ServerApplication.P_CalcFullName;
    }

    public String calcClientPort() {
        return pp + "." + ServerApplication.P_CalcClientPort;
    }

    public String calcHttpPort() {
        return pp + "." + ServerApplication.P_CalcHttpPort;
    }

    public String calcHttpsPort() {
        return pp + "." + ServerApplication.P_CalcHttpsPort;
    }

    public String calcName() {
        return pp + "." + ServerApplication.P_CalcName;
    }

    public String run() {
        return pp + ".run";
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
