// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.appstore.model.oa.*;
 
public class ServerPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public ServerPPx(String name) {
        this(null, name);
    }

    public ServerPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public AppUserPPx appUser() {
        AppUserPPx ppx = new AppUserPPx(this, Server.P_AppUser);
        return ppx;
    }

    public EnvironmentPPx environment() {
        EnvironmentPPx ppx = new EnvironmentPPx(this, Server.P_Environment);
        return ppx;
    }

    public ServerApplicationPPx serverApplications() {
        ServerApplicationPPx ppx = new ServerApplicationPPx(this, Server.P_ServerApplications);
        return ppx;
    }

    public String id() {
        return pp + "." + Server.P_Id;
    }

    public String created() {
        return pp + "." + Server.P_Created;
    }

    public String name() {
        return pp + "." + Server.P_Name;
    }

    public String host() {
        return pp + "." + Server.P_Host;
    }

    public String ipAddress() {
        return pp + "." + Server.P_IpAddress;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
