// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import com.viaoa.appstore.model.oa.*;
 
public class SingleAppPP {
    private static ApplicationTypePPx applicationType;
    private static ApplicationVersionPPx applicationVersion;
    private static AppUserPPx appUser;
    private static RunningAppPPx runningApp;
     

    public static ApplicationTypePPx applicationType() {
        if (applicationType == null) applicationType = new ApplicationTypePPx(SingleApp.P_ApplicationType);
        return applicationType;
    }

    public static ApplicationVersionPPx applicationVersion() {
        if (applicationVersion == null) applicationVersion = new ApplicationVersionPPx(SingleApp.P_ApplicationVersion);
        return applicationVersion;
    }

    public static AppUserPPx appUser() {
        if (appUser == null) appUser = new AppUserPPx(SingleApp.P_AppUser);
        return appUser;
    }

    public static RunningAppPPx runningApp() {
        if (runningApp == null) runningApp = new RunningAppPPx(SingleApp.P_RunningApp);
        return runningApp;
    }

    public static String id() {
        String s = SingleApp.P_Id;
        return s;
    }

    public static String created() {
        String s = SingleApp.P_Created;
        return s;
    }

    public static String run() {
        String s = "run";
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
