// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.appstore.model.oa.*;
 
public class SingleAppPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public SingleAppPPx(String name) {
        this(null, name);
    }

    public SingleAppPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ApplicationTypePPx applicationType() {
        ApplicationTypePPx ppx = new ApplicationTypePPx(this, SingleApp.P_ApplicationType);
        return ppx;
    }

    public ApplicationVersionPPx applicationVersion() {
        ApplicationVersionPPx ppx = new ApplicationVersionPPx(this, SingleApp.P_ApplicationVersion);
        return ppx;
    }

    public AppUserPPx appUser() {
        AppUserPPx ppx = new AppUserPPx(this, SingleApp.P_AppUser);
        return ppx;
    }

    public RunningAppPPx runningApp() {
        RunningAppPPx ppx = new RunningAppPPx(this, SingleApp.P_RunningApp);
        return ppx;
    }

    public String id() {
        return pp + "." + SingleApp.P_Id;
    }

    public String created() {
        return pp + "." + SingleApp.P_Created;
    }

    public String run() {
        return pp + ".run";
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
