// Generated by OABuilder
package com.viaoa.appstore.model.oa.propertypath;
 
import com.viaoa.appstore.model.oa.*;
 
public class VersionFilePP {
    private static ApplicationVersionPPx applicationVersion;
     

    public static ApplicationVersionPPx applicationVersion() {
        if (applicationVersion == null) applicationVersion = new ApplicationVersionPPx(VersionFile.P_ApplicationVersion);
        return applicationVersion;
    }

    public static String id() {
        String s = VersionFile.P_Id;
        return s;
    }

    public static String created() {
        String s = VersionFile.P_Created;
        return s;
    }

    public static String type() {
        String s = VersionFile.P_Type;
        return s;
    }

    public static String filePath() {
        String s = VersionFile.P_FilePath;
        return s;
    }

    public static String calcIsJarFile() {
        String s = VersionFile.P_CalcIsJarFile;
        return s;
    }

    public static String calcDownloadUrl() {
        String s = VersionFile.P_CalcDownloadUrl;
        return s;
    }

    public static String calcFilePath() {
        String s = VersionFile.P_CalcFilePath;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
