#!/bin/sh
# postinst script for oabuilder
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
xdg-desktop-menu install /home/vvia/oabuilder/lib/oabuilder-OABuilder.desktop
xdg-mime install /home/vvia/oabuilder/lib/oabuilder-OABuilder-MimeInfo.xml
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# custom
echo "Installer running from directory: " $PWD

chmod 777 ~/oabuilder
chmod 777 ~/oabuilder/lib
chmod -R 777 ~/oabuilder/lib/app

exit 0
