// Generated by OABuilder
package com.viaoa.appstore.model.oa.search;

import java.util.*;
import java.util.logging.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.util.OADateTime;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;

@OAClass(useDataSource=false, localOnly=true)
public class AppRuntimeErrorSearch extends OAObject {
    private static final long serialVersionUID = 1L;

    private static Logger LOG = Logger.getLogger(AppRuntimeErrorSearch.class.getName());

    public static final String P_Created = "Created";
    public static final String P_Created2 = "Created2";
    public static final String P_Ack = "Ack";
    public static final String P_AckUseNull = "AckUseNull";
    public static final String P_AckUseNotNull = "AckUseNotNull";
    public static final String P_Message = "Message";
    public static final String P_MaxResults = "MaxResults";

    protected OADateTime created;
    protected OADateTime created2;
    protected boolean ack;
    protected boolean ackUseNull;
    protected boolean ackUseNotNull;
    protected String message;
    protected int maxResults;

    @OAProperty(defaultValue = "new OADateTime()", displayLength = 15)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
        if (isLoading()) return;
        if (created != null) {
            if (created2 == null) setCreated2(this.created.addDays(1));
            else if (created.compareTo(created2) > 0) setCreated2(this.created.addDays(1));
        }
    } 
    public OADateTime getCreated2() {
        return created2;
    }
    public void setCreated2(OADateTime newValue) {
        OADateTime old = created2;
        fireBeforePropertyChange(P_Created2, old, newValue);
        this.created2 = newValue;
        firePropertyChange(P_Created2, old, this.created2);
        if (created != null && created2 != null) {
            if (created.compareTo(created2) > 0) setCreated(this.created2);
        }
    }
    @OAProperty(displayLength = 5)
    public boolean getAck() {
        return ack;
    }
    public boolean isAck() {
        return getAck();
    }
    public void setAck(boolean newValue) {
        boolean old = ack;
        fireBeforePropertyChange(P_Ack, old, newValue);
        this.ack = newValue;
        firePropertyChange(P_Ack, old, this.ack);
    }
      
    public boolean getAckUseNull() {
        return ackUseNull;
    }
    public void setAckUseNull(boolean newValue) {
        boolean old = this.ackUseNull;
        this.ackUseNull = newValue;
        firePropertyChange(P_AckUseNull, old, this.ackUseNull);
    }
    public boolean getAckUseNotNull() {
        return ackUseNotNull;
    }
    public void setAckUseNotNull(boolean newValue) {
        boolean old = this.ackUseNotNull;
        this.ackUseNotNull = newValue;
        firePropertyChange(P_AckUseNotNull, old, this.ackUseNotNull);
    }
    @OAProperty(displayLength = 20)
    public String getMessage() {
        return message;
    }
    public void setMessage(String newValue) {
        String old = message;
        fireBeforePropertyChange(P_Message, old, newValue);
        this.message = newValue;
        firePropertyChange(P_Message, old, this.message);
    }
      

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public void reset() {
        setCreated(null);
        setCreated2(null);
        setAck(false);
        setNull(P_Ack);
        setAckUseNull(false);
        setAckUseNotNull(false);
        setMessage(null);
    }

    public boolean isDataEntered() {
        if (getCreated() != null) return true;
        if (!isNull(P_Ack)) return true;
        if (getAckUseNull()) return true;
        if (getAckUseNotNull()) return true;
        if (getMessage() != null) return true;
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<AppRuntimeError> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<AppRuntimeError> f = new OAQueryFilter<AppRuntimeError>(AppRuntimeError.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<AppRuntimeError> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<AppRuntimeError> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<AppRuntimeError> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];
        if (created != null) {
            if (sql.length() > 0) sql += " AND ";
            if (created2 != null && !created.equals(created2)) {
                sql += AppRuntimeError.P_Created + " >= ?";
                args = OAArray.add(Object.class, args, this.created);
                sql += " AND " + AppRuntimeError.P_Created + " <= ?";
                args = OAArray.add(Object.class, args, this.created2);
            }
            else {
                sql += AppRuntimeError.P_Created + " = ?";
                args = OAArray.add(Object.class, args, this.created);
            }
        }
        if (ackUseNull) {
            if (sql.length() > 0) sql += " AND ";
            sql += AppRuntimeError.P_Ack + " = null";
        }
        else if (ackUseNotNull) {
            if (sql.length() > 0) sql += " AND ";
            sql += AppRuntimeError.P_Ack + " != null";
        }
        if (!isNull(P_Ack)) {
            if (sql.length() > 0) sql += " AND ";
            sql += AppRuntimeError.P_Ack + " = ?";
            args = OAArray.add(Object.class, args, this.ack);
        }
        if (OAString.isNotEmpty(this.message)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(message);
            if (val.indexOf("%") >= 0) {
                sql += AppRuntimeError.P_Message + " LIKE ?";
            }
            else {
                sql += AppRuntimeError.P_Message + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<AppRuntimeError> select = new OASelect<AppRuntimeError>(AppRuntimeError.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        if (created != null) {
            if (sql.length() > 0) sql += " AND ";
            if (created2 != null && !created.equals(created2)) {
                sql += prefix + AppRuntimeError.P_Created + " >= ?";
                args = OAArray.add(Object.class, args, this.created);
                sql += " AND " + prefix + AppRuntimeError.P_Created + " <= ?";
                args = OAArray.add(Object.class, args, this.created2);
            }
            else {
                sql += prefix + AppRuntimeError.P_Created + " = ?";
                args = OAArray.add(Object.class, args, this.created);
            }
        }
        if (ackUseNull) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + AppRuntimeError.P_Ack + " = null";
        }
        else if (ackUseNotNull) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + AppRuntimeError.P_Ack + " != null";
        }
        if (!isNull(P_Ack)) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + AppRuntimeError.P_Ack + " = ?";
            args = OAArray.add(Object.class, args, this.ack);
        }
        if (OAString.isNotEmpty(this.message)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(message);
            if (val.indexOf("%") >= 0) {
                sql += prefix + AppRuntimeError.P_Message + " LIKE ?";
            }
            else {
                sql += prefix + AppRuntimeError.P_Message + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        select.add(sql, args);
    }

    private OAFilter<AppRuntimeError> filterDataSourceFilter;
    public OAFilter<AppRuntimeError> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<AppRuntimeError>() {
            @Override
            public boolean isUsed(AppRuntimeError appRuntimeError) {
                return AppRuntimeErrorSearch.this.isUsedForDataSourceFilter(appRuntimeError);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<AppRuntimeError> filterCustomFilter;
    public OAFilter<AppRuntimeError> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<AppRuntimeError>() {
            @Override
            public boolean isUsed(AppRuntimeError appRuntimeError) {
                boolean b = AppRuntimeErrorSearch.this.isUsedForCustomFilter(appRuntimeError);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(AppRuntimeError searchAppRuntimeError) {
        return true;
    }
    public boolean isUsedForCustomFilter(AppRuntimeError searchAppRuntimeError) {
        return true;
    }
}
