// Generated by OABuilder
package com.viaoa.appstore.model.oa.search;

import java.util.*;
import java.util.logging.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.util.OADate;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;
import com.viaoa.appstore.resource.Resource;

@OAClass(useDataSource=false, localOnly=true)
public class AppUserSearch extends OAObject {
    private static final long serialVersionUID = 1L;

    private static Logger LOG = Logger.getLogger(AppUserSearch.class.getName());

    public static final String P_LoginId = "LoginId";
    public static final String P_FirstName = "FirstName";
    public static final String P_LastName = "LastName";
    public static final String P_InactiveDate = "InactiveDate";
    public static final String P_Id = "Id";
    public static final String P_MaxResults = "MaxResults";

    protected String loginId;
    protected String firstName;
    protected String lastName;
    protected OADate inactiveDate;
    protected int id;
    protected int maxResults;

    @OAProperty(displayName = "Login Id", maxLength = 24, displayLength = 12)
    public String getLoginId() {
        return loginId;
    }
    public void setLoginId(String newValue) {
        String old = loginId;
        fireBeforePropertyChange(P_LoginId, old, newValue);
        this.loginId = newValue;
        firePropertyChange(P_LoginId, old, this.loginId);
    }
      
    @OAProperty(displayName = "First Name", maxLength = 30, displayLength = 12)
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String newValue) {
        String old = firstName;
        fireBeforePropertyChange(P_FirstName, old, newValue);
        this.firstName = newValue;
        firePropertyChange(P_FirstName, old, this.firstName);
    }
      
    @OAProperty(displayName = "Last Name", maxLength = 55, displayLength = 12)
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String newValue) {
        String old = lastName;
        fireBeforePropertyChange(P_LastName, old, newValue);
        this.lastName = newValue;
        firePropertyChange(P_LastName, old, this.lastName);
    }
      
    @OAProperty(displayName = "Inactive Date", displayLength = 8)
    public OADate getInactiveDate() {
        return inactiveDate;
    }
    public void setInactiveDate(OADate newValue) {
        OADate old = inactiveDate;
        fireBeforePropertyChange(P_InactiveDate, old, newValue);
        this.inactiveDate = newValue;
        firePropertyChange(P_InactiveDate, old, this.inactiveDate);
    }
      
    @OAProperty(displayLength = 5)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }
      

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public void reset() {
        setLoginId(null);
        setFirstName(null);
        setLastName(null);
        setInactiveDate(null);
        setId(0);
        setNull(P_Id);
    }

    public boolean isDataEntered() {
        if (getLoginId() != null) return true;
        if (getFirstName() != null) return true;
        if (getLastName() != null) return true;
        if (getInactiveDate() != null) return true;
        if (!isNull(P_Id)) return true;
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<AppUser> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<AppUser> f = new OAQueryFilter<AppUser>(AppUser.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<AppUser> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<AppUser> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<AppUser> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];
        if (OAString.isNotEmpty(this.loginId)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(loginId);
            if (val.indexOf("%") >= 0) {
                sql += AppUser.P_LoginId + " LIKE ?";
            }
            else {
                sql += AppUser.P_LoginId + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (OAString.isNotEmpty(this.firstName)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(firstName);
            if (val.indexOf("%") >= 0) {
                sql += AppUser.P_FirstName + " LIKE ?";
            }
            else {
                sql += AppUser.P_FirstName + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (OAString.isNotEmpty(this.lastName)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(lastName);
            if (val.indexOf("%") >= 0) {
                sql += AppUser.P_LastName + " LIKE ?";
            }
            else {
                sql += AppUser.P_LastName + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (inactiveDate != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += AppUser.P_InactiveDate + " = ?";
            args = OAArray.add(Object.class, args, this.inactiveDate);
        }
        if (!isNull(P_Id)) {
            if (sql.length() > 0) sql += " AND ";
            sql += AppUser.P_Id + " = ?";
            args = OAArray.add(Object.class, args, this.id);
        }

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<AppUser> select = new OASelect<AppUser>(AppUser.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        if (OAString.isNotEmpty(this.loginId)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(loginId);
            if (val.indexOf("%") >= 0) {
                sql += prefix + AppUser.P_LoginId + " LIKE ?";
            }
            else {
                sql += prefix + AppUser.P_LoginId + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (OAString.isNotEmpty(this.firstName)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(firstName);
            if (val.indexOf("%") >= 0) {
                sql += prefix + AppUser.P_FirstName + " LIKE ?";
            }
            else {
                sql += prefix + AppUser.P_FirstName + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (OAString.isNotEmpty(this.lastName)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(lastName);
            if (val.indexOf("%") >= 0) {
                sql += prefix + AppUser.P_LastName + " LIKE ?";
            }
            else {
                sql += prefix + AppUser.P_LastName + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (inactiveDate != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + AppUser.P_InactiveDate + " = ?";
            args = OAArray.add(Object.class, args, this.inactiveDate);
        }
        if (!isNull(P_Id)) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + AppUser.P_Id + " = ?";
            args = OAArray.add(Object.class, args, this.id);
        }
        select.add(sql, args);
    }

    private OAFilter<AppUser> filterDataSourceFilter;
    public OAFilter<AppUser> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<AppUser>() {
            @Override
            public boolean isUsed(AppUser appUser) {
                return AppUserSearch.this.isUsedForDataSourceFilter(appUser);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<AppUser> filterCustomFilter;
    public OAFilter<AppUser> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<AppUser>() {
            @Override
            public boolean isUsed(AppUser appUser) {
                boolean b = AppUserSearch.this.isUsedForCustomFilter(appUser);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(AppUser searchAppUser) {
        return true;
    }
    public boolean isUsedForCustomFilter(AppUser searchAppUser) {
        return true;
    }
}
