// Generated by OABuilder
package com.viaoa.appstore.model.oa.search;

import java.util.*;
import java.util.logging.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;

@OAClass(useDataSource=false, localOnly=true)
public class ClientAppSearch extends OAObject {
    private static final long serialVersionUID = 1L;

    private static Logger LOG = Logger.getLogger(ClientAppSearch.class.getName());

    public static final String P_MaxResults = "MaxResults";

    protected int maxResults;


    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<ClientApp> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<ClientApp> f = new OAQueryFilter<ClientApp>(ClientApp.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<ClientApp> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<ClientApp> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<ClientApp> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<ClientApp> select = new OASelect<ClientApp>(ClientApp.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        select.add(sql, args);
    }

    private OAFilter<ClientApp> filterDataSourceFilter;
    public OAFilter<ClientApp> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<ClientApp>() {
            @Override
            public boolean isUsed(ClientApp clientApp) {
                return ClientAppSearch.this.isUsedForDataSourceFilter(clientApp);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<ClientApp> filterCustomFilter;
    public OAFilter<ClientApp> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<ClientApp>() {
            @Override
            public boolean isUsed(ClientApp clientApp) {
                boolean b = ClientAppSearch.this.isUsedForCustomFilter(clientApp);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(ClientApp searchClientApp) {
        return true;
    }
    public boolean isUsedForCustomFilter(ClientApp searchClientApp) {
        return true;
    }
}
