// Generated by OABuilder
package com.viaoa.appstore.model.oa.search;

import java.util.*;
import java.util.logging.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.util.OADateTime;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;
import com.viaoa.appstore.delegate.ModelDelegate;

@OAClass(useDataSource=false, localOnly=true)
public class RunningAppSearch extends OAObject {
    private static final long serialVersionUID = 1L;

    private static Logger LOG = Logger.getLogger(RunningAppSearch.class.getName());

    public static final String P_Pid = "Pid";
    public static final String P_Created = "Created";
    public static final String P_Created2 = "Created2";
    public static final String P_Stopped = "Stopped";
    public static final String P_Stopped2 = "Stopped2";
    public static final String P_Id = "Id";
    public static final String P_MaxResults = "MaxResults";

    protected long pid;
    protected OADateTime created;
    protected OADateTime created2;
    protected OADateTime stopped;
    protected OADateTime stopped2;
    protected int id;
    protected int maxResults;

    @OAProperty(displayLength = 6)
    public long getPid() {
        return pid;
    }
    public void setPid(long newValue) {
        long old = pid;
        fireBeforePropertyChange(P_Pid, old, newValue);
        this.pid = newValue;
        firePropertyChange(P_Pid, old, this.pid);
    }
      
    @OAProperty(defaultValue = "new OADateTime()", displayLength = 15)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
        if (isLoading()) return;
        if (created != null) {
            if (created2 == null) setCreated2(this.created.addDays(1));
            else if (created.compareTo(created2) > 0) setCreated2(this.created.addDays(1));
        }
    } 
    public OADateTime getCreated2() {
        return created2;
    }
    public void setCreated2(OADateTime newValue) {
        OADateTime old = created2;
        fireBeforePropertyChange(P_Created2, old, newValue);
        this.created2 = newValue;
        firePropertyChange(P_Created2, old, this.created2);
        if (created != null && created2 != null) {
            if (created.compareTo(created2) > 0) setCreated(this.created2);
        }
    }
    @OAProperty(displayLength = 15)
    public OADateTime getStopped() {
        return stopped;
    }
    public void setStopped(OADateTime newValue) {
        OADateTime old = stopped;
        fireBeforePropertyChange(P_Stopped, old, newValue);
        this.stopped = newValue;
        firePropertyChange(P_Stopped, old, this.stopped);
        if (isLoading()) return;
        if (stopped != null) {
            if (stopped2 == null) setStopped2(this.stopped.addDays(1));
            else if (stopped.compareTo(stopped2) > 0) setStopped2(this.stopped.addDays(1));
        }
    } 
    public OADateTime getStopped2() {
        return stopped2;
    }
    public void setStopped2(OADateTime newValue) {
        OADateTime old = stopped2;
        fireBeforePropertyChange(P_Stopped2, old, newValue);
        this.stopped2 = newValue;
        firePropertyChange(P_Stopped2, old, this.stopped2);
        if (stopped != null && stopped2 != null) {
            if (stopped.compareTo(stopped2) > 0) setStopped(this.stopped2);
        }
    }
    @OAProperty(displayLength = 6)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }
      

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public void reset() {
        setPid(0);
        setNull(P_Pid);
        setCreated(null);
        setCreated2(null);
        setStopped(null);
        setStopped2(null);
        setId(0);
        setNull(P_Id);
    }

    public boolean isDataEntered() {
        if (!isNull(P_Pid)) return true;
        if (getCreated() != null) return true;
        if (getStopped() != null) return true;
        if (!isNull(P_Id)) return true;
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<RunningApp> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<RunningApp> f = new OAQueryFilter<RunningApp>(RunningApp.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<RunningApp> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<RunningApp> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<RunningApp> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];
        if (!isNull(P_Pid)) {
            if (sql.length() > 0) sql += " AND ";
            sql += RunningApp.P_Pid + " = ?";
            args = OAArray.add(Object.class, args, this.pid);
        }
        if (created != null) {
            if (sql.length() > 0) sql += " AND ";
            if (created2 != null && !created.equals(created2)) {
                sql += RunningApp.P_Created + " >= ?";
                args = OAArray.add(Object.class, args, this.created);
                sql += " AND " + RunningApp.P_Created + " <= ?";
                args = OAArray.add(Object.class, args, this.created2);
            }
            else {
                sql += RunningApp.P_Created + " = ?";
                args = OAArray.add(Object.class, args, this.created);
            }
        }
        if (stopped != null) {
            if (sql.length() > 0) sql += " AND ";
            if (stopped2 != null && !stopped.equals(stopped2)) {
                sql += RunningApp.P_Stopped + " >= ?";
                args = OAArray.add(Object.class, args, this.stopped);
                sql += " AND " + RunningApp.P_Stopped + " <= ?";
                args = OAArray.add(Object.class, args, this.stopped2);
            }
            else {
                sql += RunningApp.P_Stopped + " = ?";
                args = OAArray.add(Object.class, args, this.stopped);
            }
        }
        if (!isNull(P_Id)) {
            if (sql.length() > 0) sql += " AND ";
            sql += RunningApp.P_Id + " = ?";
            args = OAArray.add(Object.class, args, this.id);
        }

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<RunningApp> select = new OASelect<RunningApp>(RunningApp.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        if (!isNull(P_Pid)) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + RunningApp.P_Pid + " = ?";
            args = OAArray.add(Object.class, args, this.pid);
        }
        if (created != null) {
            if (sql.length() > 0) sql += " AND ";
            if (created2 != null && !created.equals(created2)) {
                sql += prefix + RunningApp.P_Created + " >= ?";
                args = OAArray.add(Object.class, args, this.created);
                sql += " AND " + prefix + RunningApp.P_Created + " <= ?";
                args = OAArray.add(Object.class, args, this.created2);
            }
            else {
                sql += prefix + RunningApp.P_Created + " = ?";
                args = OAArray.add(Object.class, args, this.created);
            }
        }
        if (stopped != null) {
            if (sql.length() > 0) sql += " AND ";
            if (stopped2 != null && !stopped.equals(stopped2)) {
                sql += prefix + RunningApp.P_Stopped + " >= ?";
                args = OAArray.add(Object.class, args, this.stopped);
                sql += " AND " + prefix + RunningApp.P_Stopped + " <= ?";
                args = OAArray.add(Object.class, args, this.stopped2);
            }
            else {
                sql += prefix + RunningApp.P_Stopped + " = ?";
                args = OAArray.add(Object.class, args, this.stopped);
            }
        }
        if (!isNull(P_Id)) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + RunningApp.P_Id + " = ?";
            args = OAArray.add(Object.class, args, this.id);
        }
        select.add(sql, args);
    }

    private OAFilter<RunningApp> filterDataSourceFilter;
    public OAFilter<RunningApp> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<RunningApp>() {
            @Override
            public boolean isUsed(RunningApp runningApp) {
                return RunningAppSearch.this.isUsedForDataSourceFilter(runningApp);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<RunningApp> filterCustomFilter;
    public OAFilter<RunningApp> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<RunningApp>() {
            @Override
            public boolean isUsed(RunningApp runningApp) {
                boolean b = RunningAppSearch.this.isUsedForCustomFilter(runningApp);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(RunningApp searchRunningApp) {
        return true;
    }
    public boolean isUsedForCustomFilter(RunningApp searchRunningApp) {
        return true;
    }
}
