// Generated by OABuilder
package com.viaoa.appstore.model.oa.search;

import java.util.*;
import java.util.logging.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.util.OADateTime;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;

@OAClass(useDataSource=false, localOnly=true)
public class ServerSearch extends OAObject {
    private static final long serialVersionUID = 1L;

    private static Logger LOG = Logger.getLogger(ServerSearch.class.getName());

    public static final String P_Host = "Host";
    public static final String P_IpAddress = "IpAddress";
    public static final String P_Created = "Created";
    public static final String P_Id = "Id";
    public static final String P_Id2 = "Id2";
    public static final String P_Environment = "Environment";
    public static final String P_UseEnvironmentSearch = "UseEnvironmentSearch";
    public static final String P_ApplicationsApplicationType = "ApplicationsApplicationType";
    public static final String P_UseApplicationsApplicationTypeSearch = "UseApplicationsApplicationTypeSearch";
    public static final String P_MaxResults = "MaxResults";

    protected String host;
    protected String ipAddress;
    protected OADateTime created;
    protected int id;
    protected int id2;
    protected Environment environment;
    protected boolean useEnvironmentSearch;
    protected EnvironmentSearch searchEnvironment;
    protected ApplicationType applicationsApplicationType;
    protected boolean useApplicationsApplicationTypeSearch;
    protected ApplicationTypeSearch searchApplicationsApplicationType;
    protected int maxResults;

    @OAProperty(maxLength = 45, displayLength = 20)
    public String getHost() {
        return host;
    }
    public void setHost(String newValue) {
        String old = host;
        fireBeforePropertyChange(P_Host, old, newValue);
        this.host = newValue;
        firePropertyChange(P_Host, old, this.host);
    }
      
    @OAProperty(displayName = "Ip Address", maxLength = 20, displayLength = 20)
    public String getIpAddress() {
        return ipAddress;
    }
    public void setIpAddress(String newValue) {
        String old = ipAddress;
        fireBeforePropertyChange(P_IpAddress, old, newValue);
        this.ipAddress = newValue;
        firePropertyChange(P_IpAddress, old, this.ipAddress);
    }
      
    @OAProperty(defaultValue = "new OADateTime()", displayLength = 15)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
    }
      
    @OAProperty(displayLength = 6)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
        if (isLoading()) return;
        if (id > id2) setId2(this.id);
    } 
    public int getId2() {
        return id2;
    }
    public void setId2(int newValue) {
        int old = id2;
        fireBeforePropertyChange(P_Id2, old, newValue);
        this.id2 = newValue;
        firePropertyChange(P_Id2, old, this.id2);
        if (isLoading()) return;
        if (id > id2) setId(this.id2);
    }

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    @OAOne
    public Environment getEnvironment() {
        if (environment == null) {
            environment = (Environment) getObject(P_Environment);
        }
        return environment;
    }
    public void setEnvironment(Environment newValue) {
        Environment old = this.environment;
        this.environment = newValue;
        firePropertyChange(P_Environment, old, this.environment);
    }
    public boolean getUseEnvironmentSearch() {
        return useEnvironmentSearch;
    }
    public void setUseEnvironmentSearch(boolean newValue) {
        boolean old = this.useEnvironmentSearch;
        this.useEnvironmentSearch = newValue;
        firePropertyChange(P_UseEnvironmentSearch, old, this.useEnvironmentSearch);
    }
    public EnvironmentSearch getEnvironmentSearch() {
        return this.searchEnvironment;
    }
    public void setEnvironmentSearch(EnvironmentSearch newValue) {
        this.searchEnvironment = newValue;
    }

    @OAOne
    public ApplicationType getApplicationsApplicationType() {
        if (applicationsApplicationType == null) {
            applicationsApplicationType = (ApplicationType) getObject(P_ApplicationsApplicationType);
        }
        return applicationsApplicationType;
    }
    public void setApplicationsApplicationType(ApplicationType newValue) {
        ApplicationType old = this.applicationsApplicationType;
        this.applicationsApplicationType = newValue;
        firePropertyChange(P_ApplicationsApplicationType, old, this.applicationsApplicationType);
    }
    public boolean getUseApplicationsApplicationTypeSearch() {
        return useApplicationsApplicationTypeSearch;
    }
    public void setUseApplicationsApplicationTypeSearch(boolean newValue) {
        boolean old = this.useApplicationsApplicationTypeSearch;
        this.useApplicationsApplicationTypeSearch = newValue;
        firePropertyChange(P_UseApplicationsApplicationTypeSearch, old, this.useApplicationsApplicationTypeSearch);
    }
    public ApplicationTypeSearch getApplicationsApplicationTypeSearch() {
        return this.searchApplicationsApplicationType;
    }
    public void setApplicationsApplicationTypeSearch(ApplicationTypeSearch newValue) {
        this.searchApplicationsApplicationType = newValue;
    }

    public void reset() {
        setHost(null);
        setIpAddress(null);
        setCreated(null);
        setId(0);
        setNull(P_Id);
        setId2(0);
        setNull(P_Id2);
        setEnvironment(null);
        setUseEnvironmentSearch(false);
        setApplicationsApplicationType(null);
        setUseApplicationsApplicationTypeSearch(false);
    }

    public boolean isDataEntered() {
        if (getHost() != null) return true;
        if (getIpAddress() != null) return true;
        if (getCreated() != null) return true;
        if (!isNull(P_Id)) return true;
        if (getEnvironment() != null) return true;
        if (getUseEnvironmentSearch()) return true;
        if (getApplicationsApplicationType() != null) return true;
        if (getUseApplicationsApplicationTypeSearch()) return true;
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<Server> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<Server> f = new OAQueryFilter<Server>(Server.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<Server> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<Server> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<Server> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];
        OAFinder finder = null;
        if (OAString.isNotEmpty(this.host)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(host);
            if (val.indexOf("%") >= 0) {
                sql += Server.P_Host + " LIKE ?";
            }
            else {
                sql += Server.P_Host + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (OAString.isNotEmpty(this.ipAddress)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(ipAddress);
            if (val.indexOf("%") >= 0) {
                sql += Server.P_IpAddress + " LIKE ?";
            }
            else {
                sql += Server.P_IpAddress + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (created != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += Server.P_Created + " = ?";
            args = OAArray.add(Object.class, args, this.created);
        }
        if (!isNull(P_Id)) {
            if (sql.length() > 0) sql += " AND ";
            if (!isNull(P_Id2) && id != id2) {
                sql += Server.P_Id + " >= ?";
                args = OAArray.add(Object.class, args, getId());
                sql += " AND " + Server.P_Id + " <= ?";
                args = OAArray.add(Object.class, args, getId2());
            }
            else {
                sql += Server.P_Id + " = ?";
                args = OAArray.add(Object.class, args, getId());
            }
        }
        if (!useEnvironmentSearch && getEnvironment() != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += ServerPP.environment().pp + " = ?";
            args = OAArray.add(Object.class, args, getEnvironment());
            finder = new OAFinder<Environment, Server>(getEnvironment(), Environment.P_Servers);
        }
        if (!useApplicationsApplicationTypeSearch && getApplicationsApplicationType() != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += ServerPP.serverApplications().applicationType().pp + " = ?";
            args = OAArray.add(Object.class, args, getApplicationsApplicationType());
            String pp = ApplicationTypePP.serverApplications().server().pp;
            finder = new OAFinder<ApplicationType, Server>(getApplicationsApplicationType(), pp);
        }

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<Server> select = new OASelect<Server>(Server.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        select.setFinder(finder);
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        if (useEnvironmentSearch && getEnvironmentSearch() != null) {
            getEnvironmentSearch().appendSelect(ServerPP.environment().pp, select);
        }
        if (useApplicationsApplicationTypeSearch && getApplicationsApplicationTypeSearch() != null) {
            getApplicationsApplicationTypeSearch().appendSelect(ServerPP.serverApplications().applicationType().pp, select);
        }
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        if (OAString.isNotEmpty(this.host)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(host);
            if (val.indexOf("%") >= 0) {
                sql += prefix + Server.P_Host + " LIKE ?";
            }
            else {
                sql += prefix + Server.P_Host + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (OAString.isNotEmpty(this.ipAddress)) {
            if (sql.length() > 0) sql += " AND ";
            String val = OAString.convertToLikeSearch(ipAddress);
            if (val.indexOf("%") >= 0) {
                sql += prefix + Server.P_IpAddress + " LIKE ?";
            }
            else {
                sql += prefix + Server.P_IpAddress + " = ?";
            }
            args = OAArray.add(Object.class, args, val);
        }
        if (created != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + Server.P_Created + " = ?";
            args = OAArray.add(Object.class, args, this.created);
        }
        if (!isNull(P_Id)) {
            if (sql.length() > 0) sql += " AND ";
            if (!isNull(P_Id2) && id != id2) {
                sql += prefix + Server.P_Id + " >= ?";
                args = OAArray.add(Object.class, args, getId());
                sql += " AND " + prefix + Server.P_Id + " <= ?";
                args = OAArray.add(Object.class, args, getId2());
            }
            else {
                sql += prefix + Server.P_Id + " = ?";
                args = OAArray.add(Object.class, args, getId());
            }
        }
        if (!useEnvironmentSearch && getEnvironment() != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + ServerPP.environment().pp + " = ?";
            args = OAArray.add(Object.class, args, getEnvironment());
        }
        if (useEnvironmentSearch && getEnvironmentSearch() != null) {
            getEnvironmentSearch().appendSelect(prefix + ServerPP.environment().pp, select);
        }
        if (!useApplicationsApplicationTypeSearch && getApplicationsApplicationType() != null) {
            if (sql.length() > 0) sql += " AND ";
            sql += prefix + ServerPP.serverApplications().applicationType().pp + " = ?";
            args = OAArray.add(Object.class, args, getApplicationsApplicationType());
        }
        if (useApplicationsApplicationTypeSearch && getApplicationsApplicationTypeSearch() != null) {
            getApplicationsApplicationTypeSearch().appendSelect(prefix + ServerPP.serverApplications().applicationType().pp, select);
        }
        select.add(sql, args);
    }

    private OAFilter<Server> filterDataSourceFilter;
    public OAFilter<Server> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<Server>() {
            @Override
            public boolean isUsed(Server server) {
                return ServerSearch.this.isUsedForDataSourceFilter(server);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<Server> filterCustomFilter;
    public OAFilter<Server> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<Server>() {
            @Override
            public boolean isUsed(Server server) {
                boolean b = ServerSearch.this.isUsedForCustomFilter(server);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(Server searchServer) {
        return true;
    }
    public boolean isUsedForCustomFilter(Server searchServer) {
        return true;
    }
}
