// Generated by OABuilder
package com.viaoa.appstore.util;
import java.util.Stack;
import java.math.*;
import java.awt.Color;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.datasource.*;
import com.viaoa.util.*;
import com.viaoa.appstore.model.oa.*;
import com.viaoa.appstore.model.oa.filter.*;
import com.viaoa.appstore.delegate.*;
 
public class DataGenerator {
    OASelect sel;
    Hub hub;
    final Stack<OALinkInfo> stack = new Stack<>();
    public boolean add(OAObject obj, String linkName) {
        if (stack.size() > 20) {
            return false;
        }
        OAObjectInfo oi = OAObjectInfoDelegate.getObjectInfo(obj);
        OALinkInfo li = oi.getLinkInfo(linkName); 
        if (li == null) throw new RuntimeException("link="+linkName+", does not exist for object="+obj);
        if (stack.contains(li)) return false;
        stack.push(li);
        return true;
    }
    public void done(OAObject obj, String linkName) {
        OAObjectInfo oi = OAObjectInfoDelegate.getObjectInfo(obj);
        OALinkInfo li = oi.getLinkInfo(linkName); 
        if (li == null) throw new RuntimeException("link="+linkName+", does not exist for object="+obj);
        if (stack.pop() != li) {
            throw new RuntimeException("link="+linkName+", for object="+obj+", is not on the top of the stack");
        }
    }
    
    public ApplicationType createApplicationType() {
        ApplicationType applicationType = new ApplicationType();
        return applicationType;
    }
    
    public void prepopulate(ApplicationType obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(ApplicationType obj, int level) {
        int x;
        int tot;
    }
    
    public ApplicationVersion createApplicationVersion() {
        ApplicationVersion applicationVersion = new ApplicationVersion();
        return applicationVersion;
    }
    
    public void prepopulate(ApplicationVersion obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(ApplicationVersion obj, int level) {
        int x;
        int tot;
        if (add(obj, ApplicationVersion.P_ApplicationType)) {
            // applicationType
            //    owned
            done(obj, ApplicationVersion.P_ApplicationType);
        }
    }
    
    public AppRuntime createAppRuntime() {
        AppRuntime appRuntime = new AppRuntime();
        return appRuntime;
    }
    
    public void prepopulate(AppRuntime obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(AppRuntime obj, int level) {
        int x;
        int tot;
    }
    
    public AppRuntimeError createAppRuntimeError() {
        AppRuntimeError appRuntimeError = new AppRuntimeError();
        return appRuntimeError;
    }
    
    public void prepopulate(AppRuntimeError obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(AppRuntimeError obj, int level) {
        int x;
        int tot;
        if (add(obj, AppRuntimeError.P_AppRuntime)) {
            // appRuntime
            //    owned
            done(obj, AppRuntimeError.P_AppRuntime);
        }
    }
    
    public AppServer createAppServer() {
        AppServer appServer = new AppServer();
        return appServer;
    }
    
    public void prepopulate(AppServer obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(AppServer obj, int level) {
        int x;
        int tot;
        if (add(obj, AppServer.P_AppUserLogin)) {
            // appUserLogin
            AppUserLogin appUserLogin = null;
            if (Math.random() < .75) {
                appUserLogin = (AppUserLogin) OAObjectCacheDelegate.getRandom(AppUserLogin.class, 500);
                if (appUserLogin != null) obj.setAppUserLogin(appUserLogin);
            }
            if (appUserLogin == null) {
                appUserLogin = createAppUserLogin();
                prepopulate(appUserLogin);
                obj.setAppUserLogin(appUserLogin);
            }
            done(obj, AppServer.P_AppUserLogin);
        }
    }
    
    public AppUser createAppUser() {
        AppUser appUser = new AppUser();
        return appUser;
    }
    
    public void prepopulate(AppUser obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(AppUser obj, int level) {
        int x;
        int tot;
        if (add(obj, AppUser.P_Server)) {
            // server
            Server server = null;
            server = (Server) OAObjectCacheDelegate.getRandom(Server.class, 500);
            if (server != null) obj.setServer(server);
            done(obj, AppUser.P_Server);
        }
    }
    
    public AppUserError createAppUserError() {
        AppUserError appUserError = new AppUserError();
        return appUserError;
    }
    
    public void prepopulate(AppUserError obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(AppUserError obj, int level) {
        int x;
        int tot;
        if (add(obj, AppUserError.P_AppUserLogin)) {
            // appUserLogin
            //    owned
            done(obj, AppUserError.P_AppUserLogin);
        }
    }
    
    public AppUserLogin createAppUserLogin() {
        AppUserLogin appUserLogin = new AppUserLogin();
        return appUserLogin;
    }
    
    public void prepopulate(AppUserLogin obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(AppUserLogin obj, int level) {
        int x;
        int tot;
        if (add(obj, AppUserLogin.P_AppUser)) {
            // appUser
            //    owned
            done(obj, AppUserLogin.P_AppUser);
        }
        if (add(obj, AppUserLogin.P_RunningApp)) {
            // runningApp
            RunningApp runningApp = null;
            if (Math.random() < .75) {
                runningApp = (RunningApp) OAObjectCacheDelegate.getRandom(RunningApp.class, 500);
                if (runningApp != null) obj.setRunningApp(runningApp);
            }
            if (runningApp == null) {
                runningApp = createRunningApp();
                prepopulate(runningApp);
                obj.setRunningApp(runningApp);
            }
            done(obj, AppUserLogin.P_RunningApp);
        }
    }
    
    public ClientApp createClientApp() {
        ClientApp clientApp = new ClientApp();
        return clientApp;
    }
    
    public void prepopulate(ClientApp obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(ClientApp obj, int level) {
        int x;
        int tot;
        if (add(obj, ClientApp.P_RunningApp)) {
            // runningApp
            RunningApp runningApp = null;
            done(obj, ClientApp.P_RunningApp);
        }
    }
    
    public Environment createEnvironment() {
        Environment environment = new Environment();
        return environment;
    }
    
    public void prepopulate(Environment obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(Environment obj, int level) {
        int x;
        int tot;
    }
    
    public PropertyValue createPropertyValue() {
        PropertyValue propertyValue = new PropertyValue();
        return propertyValue;
    }
    
    public void prepopulate(PropertyValue obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(PropertyValue obj, int level) {
        int x;
        int tot;
    }
    
    public RunningApp createRunningApp() {
        RunningApp runningApp = new RunningApp();
        return runningApp;
    }
    
    public void prepopulate(RunningApp obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(RunningApp obj, int level) {
        int x;
        int tot;
    }
    
    public Server createServer() {
        Server server = new Server();
        return server;
    }
    
    public void prepopulate(Server obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(Server obj, int level) {
        int x;
        int tot;
        if (add(obj, Server.P_AppUser)) {
            // appUser
            hub = ModelDelegate.getAppUsers();
            if (Math.random() < .85) {
                x = (int) (Math.random()*hub.getSize());
                obj.setAppUser((AppUser) hub.getAt(x));
            }
            done(obj, Server.P_AppUser);
        }
        if (add(obj, Server.P_Environment)) {
            // environment
            //    owned
            done(obj, Server.P_Environment);
        }
    }
    
    public ServerApplication createServerApplication() {
        ServerApplication serverApplication = new ServerApplication();
        return serverApplication;
    }
    
    public void prepopulate(ServerApplication obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(ServerApplication obj, int level) {
        int x;
        int tot;
        if (add(obj, ServerApplication.P_ApplicationType)) {
            // applicationType
            hub = ModelDelegate.getApplicationTypes();
            x = (int) (Math.random()*hub.getSize());
            obj.setApplicationType((ApplicationType) hub.getAt(x));
            done(obj, ServerApplication.P_ApplicationType);
        }
        if (add(obj, ServerApplication.P_RunningApp)) {
            // runningApp
            RunningApp runningApp = null;
            if (Math.random() < .75) {
                runningApp = (RunningApp) OAObjectCacheDelegate.getRandom(RunningApp.class, 500);
                if (runningApp != null) obj.setRunningApp(runningApp);
            }
            if (runningApp == null) {
                runningApp = createRunningApp();
                prepopulate(runningApp);
                obj.setRunningApp(runningApp);
            }
            done(obj, ServerApplication.P_RunningApp);
        }
        if (add(obj, ServerApplication.P_Server)) {
            // server
            //    owned
            done(obj, ServerApplication.P_Server);
        }
    }
    
    public SingleApp createSingleApp() {
        SingleApp singleApp = new SingleApp();
        return singleApp;
    }
    
    public void prepopulate(SingleApp obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(SingleApp obj, int level) {
        int x;
        int tot;
        if (add(obj, SingleApp.P_AppUser)) {
            // appUser
            //    owned
            done(obj, SingleApp.P_AppUser);
        }
        if (add(obj, SingleApp.P_RunningApp)) {
            // runningApp
            RunningApp runningApp = null;
            done(obj, SingleApp.P_RunningApp);
        }
    }
    
    public VersionFile createVersionFile() {
        VersionFile versionFile = new VersionFile();
        return versionFile;
    }
    
    public void prepopulate(VersionFile obj) {
        prepopulate(obj, 0);
    }
    public void prepopulate(VersionFile obj, int level) {
        int x;
        int tot;
        if (add(obj, VersionFile.P_ApplicationVersion)) {
            // applicationVersion
            //    owned
            done(obj, VersionFile.P_ApplicationVersion);
        }
    }
    
    public void populate(ApplicationType obj) {
        populate(obj, 0);
    }
    public void populate(ApplicationType obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(14, 0, 40));
        obj.setAbbrevName(OAString.getDummyText(8, 0, 8));
        obj.setSingleTypeOnly(Math.random() < .5 ? true : false);
        obj.setClientPort((int) (Math.random() * 900));
        obj.setHttpPort((int) (Math.random() * 900));
        obj.setHttpsPort((int) (Math.random() * 900));
        // downloadUrl has a default value
        // appDirectory has a default value
        obj.setJarFileName(OAString.getDummyText(15, 0, 70));
        // mainClass has a default value
        // jvmOptions has a default value
        obj.setIcon(new byte[0]);
        obj.setConsole(OAString.getDummyText(20, 0, 254));
        if (add(obj, ApplicationType.P_ApplicationVersions)) {
            // applicationVersions
            tot = ((int) (Math.random()*4));
            tot -= obj.getApplicationVersions().size();
            for (int cnt=0; cnt<tot; cnt++) {
                ApplicationVersion applicationVersion = null;
            }
            done(obj, ApplicationType.P_ApplicationVersions);
        }
        if (add(obj, ApplicationType.P_AppUsers)) {
            // appUsers
            tot = ((int) (Math.random()*4));
            tot -= obj.getAppUsers().size();
            for (int cnt=0; cnt<tot; cnt++) {
                hub = ModelDelegate.getAppUsers();
                if (Math.random() < .75) {
                    x = (int) (Math.random()*hub.getSize());
                    obj.getAppUsers().add((AppUser) hub.getAt(x));
                }
            }
            done(obj, ApplicationType.P_AppUsers);
        }
        if (add(obj, ApplicationType.P_PropertyValues)) {
            // propertyValues
            tot = ((int) (Math.random()*4));
            tot -= obj.getPropertyValues().size();
            for (int cnt=0; cnt<tot; cnt++) {
                PropertyValue propertyValue = null;
                if (Math.random() < .75) {
                    propertyValue = (PropertyValue) OAObjectCacheDelegate.getRandom(PropertyValue.class, 500);
                    if (propertyValue != null) obj.getPropertyValues().add(propertyValue);
                }
                if (propertyValue == null) {
                    propertyValue = createPropertyValue();
                    obj.getPropertyValues().add(propertyValue);
                    populate(propertyValue);
                }
            }
            done(obj, ApplicationType.P_PropertyValues);
        }
        if (add(obj, ApplicationType.P_ServerApplications)) {
            // serverApplications
            //   will be created by Server
            done(obj, ApplicationType.P_ServerApplications);
        }
    }
    
    public void populate(ApplicationVersion obj) {
        populate(obj, 0);
    }
    public void populate(ApplicationVersion obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setVersion(OAString.getDummyText(6, 0, 12));
        obj.setRelease((int) (Math.random() * 900));
        obj.setCompleted((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setVerified((new OADateTime()).addDays((int) (Math.random() * 1000)));
        if (add(obj, ApplicationVersion.P_VersionFiles)) {
            // versionFiles
            tot = ((int) (Math.random()*4));
            tot -= obj.getVersionFiles().size();
            for (int cnt=0; cnt<tot; cnt++) {
                VersionFile versionFile = null;
            }
            done(obj, ApplicationVersion.P_VersionFiles);
        }
    }
    
    public void populate(AppRuntime obj) {
        populate(obj, 0);
    }
    public void populate(AppRuntime obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setEnvName(OAString.getDummyText(20, 0, 20));
        obj.setIsProd(Math.random() < .5 ? true : false);
        obj.setStarted((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setStopped((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setVersion(OAString.getDummyText(20, 0, 20));
        obj.setConsole(OAString.getDummyText(20, 0, 254));
        if (add(obj, AppRuntime.P_AppRuntimeErrors)) {
            // appRuntimeErrors
            tot = ((int) (Math.random()*4));
            tot -= obj.getAppRuntimeErrors().size();
            for (int cnt=0; cnt<tot; cnt++) {
                AppRuntimeError appRuntimeError = null;
                appRuntimeError = createAppRuntimeError();
                obj.getAppRuntimeErrors().add(appRuntimeError);
                populate(appRuntimeError);
            }
            done(obj, AppRuntime.P_AppRuntimeErrors);
        }
    }
    
    public void populate(AppRuntimeError obj) {
        populate(obj, 0);
    }
    public void populate(AppRuntimeError obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setMessage(OAString.getDummyText(20, 0, 0));
        obj.setAck(Math.random() < .5 ? true : false);
        obj.setStackTrace(OAString.getDummyText(30, 0, 500));
    }
    
    public void populate(AppServer obj) {
        populate(obj, 0);
    }
    public void populate(AppServer obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setStarted((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setDemoMode(Math.random() < .5 ? true : false);
        obj.setRelease(OAString.getDummyText(18, 0, 18));
    }
    
    public void populate(AppUser obj) {
        populate(obj, 0);
    }
    public void populate(AppUser obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        obj.setLoginId(OAString.getDummyText(12, 0, 24));
        obj.setPassword(OAString.getDummyText(12, 0, 50));
        obj.setAdmin(Math.random() < .5 ? true : false);
        obj.setSuperAdmin(Math.random() < .5 ? true : false);
        obj.setEditProcessed(Math.random() < .5 ? true : false);
        obj.setFirstName(OAString.getDummyText(12, 0, 30));
        obj.setLastName(OAString.getDummyText(12, 0, 55));
        if (Math.random() < .8) obj.setInactiveDate((OADate)(new OADate()).addDays((int) (Math.random() * 1000)));
        obj.setNote(OAString.getDummyText(20, 0, 500));
        obj.setDisableAutoLogin(Math.random() < .5 ? true : false);
        if (add(obj, AppUser.P_ApplicationTypes)) {
            // applicationTypes
            tot = ((int) (Math.random()*4));
            tot -= obj.getApplicationTypes().size();
            for (int cnt=0; cnt<tot; cnt++) {
                hub = ModelDelegate.getApplicationTypes();
                if (Math.random() < .75) {
                    x = (int) (Math.random()*hub.getSize());
                    obj.getApplicationTypes().add((ApplicationType) hub.getAt(x));
                }
            }
            done(obj, AppUser.P_ApplicationTypes);
        }
        if (add(obj, AppUser.P_AppUserLogins)) {
            // appUserLogins
            tot = ((int) (Math.random()*4));
            tot -= obj.getAppUserLogins().size();
            for (int cnt=0; cnt<tot; cnt++) {
                AppUserLogin appUserLogin = null;
                appUserLogin = createAppUserLogin();
                obj.getAppUserLogins().add(appUserLogin);
                populate(appUserLogin);
            }
            done(obj, AppUser.P_AppUserLogins);
        }
        if (add(obj, AppUser.P_SingleApps)) {
            // singleApps
            tot = ((int) (Math.random()*4));
            tot -= obj.getSingleApps().size();
            for (int cnt=0; cnt<tot; cnt++) {
                SingleApp singleApps = createSingleApp();
                obj.getSingleApps().add(singleApps);
                populate(singleApps);
            }
            done(obj, AppUser.P_SingleApps);
        }
    }
    
    public void populate(AppUserError obj) {
        populate(obj, 0);
    }
    public void populate(AppUserError obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        obj.setDateTime((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setMessage(OAString.getDummyText(35, 0, 250));
        obj.setStackTrace(OAString.getDummyText(40, 0, 500));
        obj.setReviewed((OADate)(new OADate()).addDays((int) (Math.random() * 1000)));
        obj.setReviewNote(OAString.getDummyText(40, 0, 254));
    }
    
    public void populate(AppUserLogin obj) {
        populate(obj, 0);
    }
    public void populate(AppUserLogin obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setLocation(OAString.getDummyText(18, 0, 50));
        obj.setComputerName(OAString.getDummyText(32, 0, 32));
        obj.setTimeZone(null);
        obj.setDisconnected((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setConnectionId((int) (Math.random() * 900));
        obj.setHostName(OAString.getDummyText(14, 0, 35));
        obj.setIpAddress(OAString.getDummyText(15, 0, 20));
        obj.setTotalMemory((long) (Math.random() * 900));
        obj.setFreeMemory((long) (Math.random() * 900));
        if (add(obj, AppUserLogin.P_AppUserErrors)) {
            // appUserErrors
            tot = ((int) (Math.random()*4));
            tot -= obj.getAppUserErrors().size();
            for (int cnt=0; cnt<tot; cnt++) {
                AppUserError appUserError = null;
                appUserError = createAppUserError();
                obj.getAppUserErrors().add(appUserError);
                populate(appUserError);
            }
            done(obj, AppUserLogin.P_AppUserErrors);
        }
    }
    
    public void populate(ClientApp obj) {
        populate(obj, 0);
    }
    public void populate(ClientApp obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(18, 0, 55));
        obj.setAutoLogin(Math.random() < .5 ? true : false);
        if (obj.getAppUser() == null) {
            hub = ModelDelegate.getAppUsers();
            x = (int) (Math.random()*hub.getSize());
            obj.setAppUser((AppUser) hub.getAt(x));
        }
        if (add(obj, ClientApp.P_PropertyValues)) {
            // propertyValues
            tot = ((int) (Math.random()*4));
            tot -= obj.getPropertyValues().size();
            for (int cnt=0; cnt<tot; cnt++) {
                PropertyValue propertyValue = null;
                propertyValue = createPropertyValue();
                obj.getPropertyValues().add(propertyValue);
                populate(propertyValue);
            }
            done(obj, ClientApp.P_PropertyValues);
        }
        if (add(obj, ClientApp.P_ServerApplication)) {
            // serverApplication
            hub = (Hub) obj.getProperty(OAString.cpp(ClientApp.P_AppUser, AppUser.P_MergeServerApplications));
            if (hub != null) {
                x = (int) (Math.random()*hub.getSize());
                obj.setServerApplication((ServerApplication) hub.getAt(x));
            }
            done(obj, ClientApp.P_ServerApplication);
        }
    }
    
    public void populate(Environment obj) {
        populate(obj, 0);
    }
    public void populate(Environment obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(15, 0, 35));
        obj.setAbbrevName(OAString.getDummyText(5, 0, 8));
        obj.setType((int) (Math.random() * 9));
        // seq is auto sequence
        if (add(obj, Environment.P_Servers)) {
            // servers
            tot = ((int) (Math.random()*4));
            tot -= obj.getServers().size();
            for (int cnt=0; cnt<tot; cnt++) {
                Server server = null;
                server = createServer();
                obj.getServers().add(server);
                populate(server);
            }
            done(obj, Environment.P_Servers);
        }
    }
    
    public void populate(PropertyValue obj) {
        populate(obj, 0);
    }
    public void populate(PropertyValue obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(18, 0, 35));
        obj.setValue(OAString.getDummyText(22, 0, 250));
        obj.setIgnore(Math.random() < .5 ? true : false);
        obj.setNote(OAString.getDummyText(22, 0, 120));
    }
    
    public void populate(RunningApp obj) {
        populate(obj, 0);
    }
    public void populate(RunningApp obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setPid((long) (Math.random() * 900));
        obj.setStopped((new OADateTime()).addDays((int) (Math.random() * 1000)));
        obj.setConfigText(OAString.getDummyText(30, 0, 500));
        obj.setConsole(OAString.getDummyText(20, 0, 254));
    }
    
    public void populate(Server obj) {
        populate(obj, 0);
    }
    public void populate(Server obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(20, 0, 55));
        obj.setHost(OAString.getDummyText(20, 0, 45));
        obj.setIpAddress(OAString.getDummyText(20, 15, 20));
        if (add(obj, Server.P_ServerApplications)) {
            // serverApplications
            tot = ((int) (Math.random()*4));
            tot -= obj.getServerApplications().size();
            for (int cnt=0; cnt<tot; cnt++) {
                ServerApplication serverApplications = createServerApplication();
                obj.getServerApplications().add(serverApplications);
                populate(serverApplications);
            }
            done(obj, Server.P_ServerApplications);
        }
    }
    
    public void populate(ServerApplication obj) {
        populate(obj, 0);
    }
    public void populate(ServerApplication obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(18, 0, 55));
        obj.setClientPort((int) (Math.random() * 900));
        obj.setHttpPort((int) (Math.random() * 900));
        obj.setHttpsPort((int) (Math.random() * 900));
        obj.setLastConnect((new OADateTime()).addDays((int) (Math.random() * 1000)));
        if (add(obj, ServerApplication.P_ApplicationVersion)) {
            // applicationVersion
            hub = (Hub) obj.getProperty(OAString.cpp(ServerApplication.P_ApplicationType, ApplicationType.P_ApplicationVersions));
            if (hub != null) {
                x = (int) (Math.random()*hub.getSize());
                obj.setApplicationVersion((ApplicationVersion) hub.getAt(x));
            }
            done(obj, ServerApplication.P_ApplicationVersion);
        }
        if (add(obj, ServerApplication.P_ClientApps)) {
            // clientApps
            //   will be created by AppUser
            done(obj, ServerApplication.P_ClientApps);
        }
        if (add(obj, ServerApplication.P_PropertyValues)) {
            // propertyValues
            tot = ((int) (Math.random()*4));
            tot -= obj.getPropertyValues().size();
            for (int cnt=0; cnt<tot; cnt++) {
                PropertyValue propertyValue = null;
                propertyValue = createPropertyValue();
                obj.getPropertyValues().add(propertyValue);
                populate(propertyValue);
            }
            done(obj, ServerApplication.P_PropertyValues);
        }
    }
    
    public void populate(SingleApp obj) {
        populate(obj, 0);
    }
    public void populate(SingleApp obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setName(OAString.getDummyText(18, 0, 55));
        if (add(obj, SingleApp.P_ApplicationType)) {
            // applicationType
            hub = (Hub) obj.getProperty(OAString.cpp(SingleApp.P_AppUser, AppUser.P_ApplicationTypes));
            if (hub != null) {
                x = (int) (Math.random()*hub.getSize());
                obj.setApplicationType((ApplicationType) hub.getAt(x));
            }
            done(obj, SingleApp.P_ApplicationType);
        }
        if (add(obj, SingleApp.P_ApplicationVersion)) {
            // applicationVersion
            hub = (Hub) obj.getProperty(OAString.cpp(SingleApp.P_ApplicationType, ApplicationType.P_ApplicationVersions));
            if (hub != null) {
                x = (int) (Math.random()*hub.getSize());
                obj.setApplicationVersion((ApplicationVersion) hub.getAt(x));
            }
            done(obj, SingleApp.P_ApplicationVersion);
        }
        if (add(obj, SingleApp.P_PropertyValues)) {
            // propertyValues
            tot = ((int) (Math.random()*4));
            tot -= obj.getPropertyValues().size();
            for (int cnt=0; cnt<tot; cnt++) {
                PropertyValue propertyValue = null;
                propertyValue = createPropertyValue();
                obj.getPropertyValues().add(propertyValue);
                populate(propertyValue);
            }
            done(obj, SingleApp.P_PropertyValues);
        }
    }
    
    public void populate(VersionFile obj) {
        populate(obj, 0);
    }
    public void populate(VersionFile obj, int level) {
        int x;
        int tot;
        // id is auto assigned
        // created has a default value
        obj.setType((int) (Math.random() * 7));
        obj.setFilePath(OAString.getDummyText(22, 0, 125));
    }
    public void createSamples() {
        int x;
        // lookups
        x = 5 + ((int) (Math.random()*20));
        for (int i=0; i<x; i++) {
            ApplicationType applicationType = createApplicationType();
            ModelDelegate.getApplicationTypes().add(applicationType);
        }
        x = 1;
        for (int i=0; i<x; i++) {
            AppRuntime appRuntime = createAppRuntime();
            ModelDelegate.getCreateOneAppRuntimeHub().add(appRuntime);
        }
        x = 1;
        for (int i=0; i<x; i++) {
            AppServer appServer = createAppServer();
            ModelDelegate.getCreateOneAppServerHub().add(appServer);
        }
        x = 5 + ((int) (Math.random()*20));
        for (int i=0; i<x; i++) {
            AppUser appUser = createAppUser();
            ModelDelegate.getAppUsers().add(appUser);
        }
        x = 5 + ((int) (Math.random()*20));
        for (int i=0; i<x; i++) {
            Environment environment = createEnvironment();
            ModelDelegate.getEnvironments().add(environment);
        }
        
        // others
        x = 5 + ((int) (Math.random()*20));
        for (int i=0; i<x; i++) {
            PropertyValue propertyValue = createPropertyValue();
            hubPropertyValue.add(propertyValue);
        }
        x = 5 + ((int) (Math.random()*20));
        for (int i=0; i<x; i++) {
            RunningApp runningApp = createRunningApp();
            hubRunningApp.add(runningApp);
        }
         
        // Now prepopulate new objects
        // lookups
        for (ApplicationType applicationType : ModelDelegate.getApplicationTypes()) {
            prepopulate(applicationType);
        }
        for (AppRuntime appRuntime : ModelDelegate.getCreateOneAppRuntimeHub()) {
            prepopulate(appRuntime);
        }
        for (AppServer appServer : ModelDelegate.getCreateOneAppServerHub()) {
            prepopulate(appServer);
        }
        for (AppUser appUser : ModelDelegate.getAppUsers()) {
            prepopulate(appUser);
        }
        for (Environment environment : ModelDelegate.getEnvironments()) {
            prepopulate(environment);
        }
        
        // others
        for (PropertyValue propertyValue : hubPropertyValue) {
            prepopulate(propertyValue);
        }
        for (RunningApp runningApp : hubRunningApp) {
            prepopulate(runningApp);
        }
        
        // Now populate new objects
        // lookups
        for (ApplicationType applicationType : ModelDelegate.getApplicationTypes()) {
            populate(applicationType);
        }
        for (AppRuntime appRuntime : ModelDelegate.getCreateOneAppRuntimeHub()) {
            populate(appRuntime);
        }
        for (AppServer appServer : ModelDelegate.getCreateOneAppServerHub()) {
            populate(appServer);
        }
        for (AppUser appUser : ModelDelegate.getAppUsers()) {
            populate(appUser);
        }
        for (Environment environment : ModelDelegate.getEnvironments()) {
            populate(environment);
        }
        
        // others
        for (PropertyValue propertyValue : hubPropertyValue) {
            populate(propertyValue);
        }
        for (RunningApp runningApp : hubRunningApp) {
            populate(runningApp);
        }
    }
    
    // Hubs to hold sample data that is not in ModelDelegate
    private Hub<PropertyValue> hubPropertyValue = new Hub<PropertyValue>(PropertyValue.class);
    private Hub<RunningApp> hubRunningApp = new Hub<RunningApp>(RunningApp.class);
    
    public static void main(String[] args) {
        OAObjectCallbackDelegate.demoAllowAllToPass(true);
        DataGenerator dg = new DataGenerator();
        dg.createSamples();
        System.out.println("createSamples is done");
    }
}
 
